"""
Seed 100 high-quality German recipes into Supabase.
Run with: python seed_recipes.py

Uses Supabase service role key from environment.
"""

import os
import json
import uuid
from datetime import datetime

# Load env
from dotenv import load_dotenv
load_dotenv()

from supabase import create_client

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)


def insert_recipe(r):
    """Insert a single recipe with ingredients and instructions."""
    recipe_data = {
        "name": r["name"],
        "description": r["description"],
        "image_url": r["image_url"],
        "prep_time": r["prep_time"],
        "cook_time": r["cook_time"],
        "servings": r["servings"],
        "difficulty": r["difficulty"],
        "calories": r.get("calories"),
        "protein": r.get("protein"),
        "carbs": r.get("carbs"),
        "fat": r.get("fat"),
        "fiber": r.get("fiber"),
    }

    result = supabase.table("recipes").insert(recipe_data).execute()
    recipe_id = result.data[0]["id"]

    # Insert ingredients
    for i, ing in enumerate(r["ingredients"]):
        supabase.table("recipe_ingredients").insert({
            "recipe_id": recipe_id,
            "ingredient_name": ing["name"],
            "quantity": str(ing["quantity"]),
            "unit": ing["unit"],
            "is_optional": ing.get("optional", False),
            "ingredient_order": i + 1,
        }).execute()

    # Insert instructions
    for i, step in enumerate(r["instructions"]):
        supabase.table("recipe_instructions").insert({
            "recipe_id": recipe_id,
            "step_number": i + 1,
            "instruction": step,
        }).execute()

    return recipe_id


RECIPES = [
    # ===================== FLEISCH & GEFLUEGEL =====================
    {
        "name": "Klassisches Wiener Schnitzel",
        "description": "Zartes Kalbsschnitzel in goldener Panade, serviert mit Zitrone und Kartoffelsalat.",
        "image_url": "https://images.unsplash.com/photo-1599921841143-819065a55cc6?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 10, "servings": 4, "difficulty": "medium",
        "calories": 520, "protein": 35, "carbs": 30, "fat": 28, "fiber": 1,
        "ingredients": [
            {"name": "Kalbsschnitzel", "quantity": "4", "unit": "Stueck"},
            {"name": "Eier", "quantity": "3", "unit": "Stueck"},
            {"name": "Semmelbrösel", "quantity": "200", "unit": "g"},
            {"name": "Mehl", "quantity": "100", "unit": "g"},
            {"name": "Butterschmalz", "quantity": "200", "unit": "g"},
            {"name": "Zitrone", "quantity": "1", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Schnitzel zwischen Frischhaltefolie duenn klopfen (ca. 5mm).",
            "Drei Teller vorbereiten: Mehl, verquirlte Eier, Semmelbrösel.",
            "Schnitzel salzen und pfeffern, dann nacheinander in Mehl, Ei und Semmelbrösel wenden.",
            "Butterschmalz in einer grossen Pfanne auf 170°C erhitzen.",
            "Schnitzel schwimmend ausbacken, dabei die Pfanne leicht schwenken, bis die Panade goldbraun ist (ca. 3-4 Min pro Seite).",
            "Auf Kuechenpapier abtropfen lassen und sofort mit Zitronenspalten servieren.",
        ],
    },
    {
        "name": "Haehnchen-Geschnetzeltes mit Pilzen",
        "description": "Cremiges Geschnetzeltes mit frischen Champignons in einer feinen Sahnesauce.",
        "image_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 20, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 32, "carbs": 8, "fat": 24, "fiber": 2,
        "ingredients": [
            {"name": "Haehnchenbrustfilet", "quantity": "600", "unit": "g"},
            {"name": "Champignons", "quantity": "300", "unit": "g"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Sahne", "quantity": "200", "unit": "ml"},
            {"name": "Huehnerbouillon", "quantity": "100", "unit": "ml"},
            {"name": "Butter", "quantity": "30", "unit": "g"},
            {"name": "Petersilie", "quantity": "1", "unit": "Bund"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
            {"name": "Paprikapulver", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Haehnchenbrustfilet in feine Streifen schneiden.",
            "Champignons putzen und in Scheiben schneiden, Zwiebel fein wuerfeln.",
            "Butter in einer Pfanne erhitzen, Haehnchenstreifen bei starker Hitze 3 Min anbraten, herausnehmen.",
            "Zwiebel und Pilze in derselben Pfanne 5 Min anbraten.",
            "Mit Bouillon ablöschen, Sahne hinzufuegen und 5 Min einkochen lassen.",
            "Haehnchen zurueck in die Sauce geben, mit Salz, Pfeffer und Paprika abschmecken.",
            "Mit gehackter Petersilie bestreuen und mit Reis oder Spaetzle servieren.",
        ],
    },
    {
        "name": "Rindergulasch nach Omas Art",
        "description": "Deftiger Rindergulasch mit Paprika, langsam geschmort bis das Fleisch zart zerfaellt.",
        "image_url": "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 120, "servings": 6, "difficulty": "medium",
        "calories": 450, "protein": 38, "carbs": 12, "fat": 26, "fiber": 3,
        "ingredients": [
            {"name": "Rindfleisch (Schulter)", "quantity": "1", "unit": "kg"},
            {"name": "Zwiebeln", "quantity": "4", "unit": "Stueck"},
            {"name": "Paprikapulver edelsüß", "quantity": "2", "unit": "EL"},
            {"name": "Tomatenmark", "quantity": "2", "unit": "EL"},
            {"name": "Rinderfond", "quantity": "500", "unit": "ml"},
            {"name": "Rote Paprika", "quantity": "2", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "3", "unit": "Zehe"},
            {"name": "Kuemmel", "quantity": "1", "unit": "TL"},
            {"name": "Öl", "quantity": "3", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Rindfleisch in 3cm grosse Wuerfel schneiden, trocken tupfen.",
            "Öl in einem Brater stark erhitzen, Fleisch portionsweise scharf anbraten. Herausnehmen.",
            "Zwiebeln in Ringe schneiden, im Bratfett goldbraun anbraten (ca. 10 Min).",
            "Paprikapulver und Tomatenmark hinzufuegen, kurz mitrösten.",
            "Mit Rinderfond ablöschen, Fleisch zurueckgeben, Kuemmel und Knoblauch zufuegen.",
            "Bei niedriger Hitze zugedeckt 1,5 Stunden schmoren.",
            "Paprika in Streifen schneiden, die letzten 30 Min mitschmoren.",
            "Mit Salz und Pfeffer abschmecken. Dazu passen Kartoffeln oder Knoedel.",
        ],
    },
    {
        "name": "Schweinelendchen mit Honig-Senf-Kruste",
        "description": "Zartes Schweinefilet mit einer aromatischen Honig-Senf-Kruste aus dem Ofen.",
        "image_url": "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 25, "servings": 4, "difficulty": "medium",
        "calories": 340, "protein": 36, "carbs": 12, "fat": 16, "fiber": 1,
        "ingredients": [
            {"name": "Schweinefilet", "quantity": "600", "unit": "g"},
            {"name": "Dijon-Senf", "quantity": "3", "unit": "EL"},
            {"name": "Honig", "quantity": "2", "unit": "EL"},
            {"name": "Semmelbrösel", "quantity": "50", "unit": "g"},
            {"name": "Rosmarin", "quantity": "2", "unit": "Stange"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Schweinefilet salzen, pfeffern und in heissem Olivenöl rundherum scharf anbraten.",
            "Senf mit Honig, gepresstem Knoblauch und gehacktem Rosmarin verrühren.",
            "Filet mit der Senf-Honig-Mischung bestreichen und in Semmelbrösel wälzen.",
            "In eine Auflaufform legen und 20-25 Min im Ofen garen (Kerntemperatur 62°C).",
            "5 Min ruhen lassen, dann in Scheiben aufschneiden und servieren.",
        ],
    },
    {
        "name": "Putenroulade mit Spinat und Feta",
        "description": "Saftige Putenrouladen gefuellt mit Blattspinat und cremigem Feta.",
        "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop",
        "prep_time": 25, "cook_time": 35, "servings": 4, "difficulty": "medium",
        "calories": 310, "protein": 38, "carbs": 5, "fat": 15, "fiber": 2,
        "ingredients": [
            {"name": "Putenschnitzel", "quantity": "4", "unit": "Stueck"},
            {"name": "Blattspinat", "quantity": "200", "unit": "g"},
            {"name": "Feta", "quantity": "150", "unit": "g"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Sonnengetrocknete Tomaten", "quantity": "50", "unit": "g"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Huehnerbouillon", "quantity": "200", "unit": "ml"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Putenschnitzel flach klopfen, salzen und pfeffern.",
            "Spinat kurz in der Pfanne zusammenfallen lassen, mit Knoblauch wuerzen.",
            "Feta zerbröseln, getrocknete Tomaten klein schneiden.",
            "Spinat, Feta und Tomaten auf den Schnitzeln verteilen und aufrollen.",
            "Mit Zahnstochern fixieren, in Olivenöl anbraten.",
            "Mit Bouillon ablöschen und zugedeckt 25 Min schmoren lassen.",
            "Rouladen herausnehmen, Sauce einreduzieren und darüber geben.",
        ],
    },
    # ===================== PASTA & NUDELN =====================
    {
        "name": "Spaghetti Carbonara",
        "description": "Original italienische Carbonara mit Guanciale, Pecorino und cremiger Ei-Sauce.",
        "image_url": "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 550, "protein": 22, "carbs": 58, "fat": 26, "fiber": 2,
        "ingredients": [
            {"name": "Spaghetti", "quantity": "400", "unit": "g"},
            {"name": "Speck (Guanciale oder Pancetta)", "quantity": "200", "unit": "g"},
            {"name": "Eigelb", "quantity": "4", "unit": "Stueck"},
            {"name": "Parmesan", "quantity": "80", "unit": "g"},
            {"name": "Pecorino", "quantity": "40", "unit": "g"},
            {"name": "Schwarzer Pfeffer", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Spaghetti in reichlich Salzwasser al dente kochen. 1 Tasse Nudelwasser aufheben.",
            "Speck in Wuerfel schneiden und ohne Fett knusprig braten.",
            "Eigelb mit geriebenem Parmesan und Pecorino vermengen, reichlich Pfeffer dazu.",
            "Spaghetti abgiessen, sofort zum Speck in die Pfanne geben (Herd aus!).",
            "Ei-Kaese-Mischung schnell unterruehren. Bei Bedarf etwas Nudelwasser zugeben fuer Cremigkeit.",
            "Sofort servieren mit extra Kaese und Pfeffer.",
        ],
    },
    {
        "name": "One-Pot Pasta mit Tomate und Basilikum",
        "description": "Alles in einen Topf - einfache Pasta mit frischen Tomaten und Basilikum in 20 Minuten.",
        "image_url": "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&h=600&fit=crop",
        "prep_time": 5, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 420, "protein": 14, "carbs": 68, "fat": 10, "fiber": 4,
        "ingredients": [
            {"name": "Penne", "quantity": "400", "unit": "g"},
            {"name": "Kirschtomaten", "quantity": "400", "unit": "g"},
            {"name": "Knoblauch", "quantity": "3", "unit": "Zehe"},
            {"name": "Basilikum", "quantity": "1", "unit": "Bund"},
            {"name": "Olivenöl", "quantity": "3", "unit": "EL"},
            {"name": "Gemüsebrühe", "quantity": "800", "unit": "ml"},
            {"name": "Parmesan", "quantity": "50", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Chiliflocken", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Kirschtomaten halbieren, Knoblauch in Scheiben schneiden.",
            "Alles ausser Basilikum und Parmesan in einen grossen Topf geben.",
            "Zum Kochen bringen und bei mittlerer Hitze 12-15 Min kochen bis die Pasta gar ist.",
            "Regelmaessig umruehren damit nichts ansetzt.",
            "Vom Herd nehmen, Parmesan und zerrissenes Basilikum unterheben.",
            "Sofort servieren.",
        ],
    },
    {
        "name": "Lasagne Bolognese",
        "description": "Klassische Lasagne mit herzhafter Bolognese und cremiger Bechamelsauce.",
        "image_url": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&h=600&fit=crop",
        "prep_time": 30, "cook_time": 45, "servings": 6, "difficulty": "medium",
        "calories": 580, "protein": 30, "carbs": 45, "fat": 30, "fiber": 3,
        "ingredients": [
            {"name": "Lasagneplatten", "quantity": "250", "unit": "g"},
            {"name": "Rinderhackfleisch", "quantity": "500", "unit": "g"},
            {"name": "Passierte Tomaten", "quantity": "500", "unit": "ml"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Karotte", "quantity": "1", "unit": "Stueck"},
            {"name": "Sellerie", "quantity": "1", "unit": "Stange"},
            {"name": "Milch", "quantity": "500", "unit": "ml"},
            {"name": "Butter", "quantity": "40", "unit": "g"},
            {"name": "Mehl", "quantity": "40", "unit": "g"},
            {"name": "Mozzarella", "quantity": "200", "unit": "g"},
            {"name": "Parmesan", "quantity": "60", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Fuer die Bolognese: Zwiebel, Karotte und Sellerie fein wuerfeln, in Olivenöl anschwitzen.",
            "Hackfleisch zugeben, kruemelig anbraten, mit passierten Tomaten ablöschen.",
            "30 Min bei niedriger Hitze köcheln lassen, mit Salz und Pfeffer wuerzen.",
            "Bechamelsauce: Butter schmelzen, Mehl einruehren, Milch langsam zugiessen und glattrühren.",
            "Mit Muskatnuss, Salz und Pfeffer abschmecken.",
            "Auflaufform schichten: Bolognese, Lasagneplatten, Bechamel — 3x wiederholen.",
            "Mit Mozzarella und Parmesan bestreuen.",
            "Bei 180°C Umluft 35-40 Min backen bis die Oberflaeche goldbraun ist.",
        ],
    },
    {
        "name": "Cremige Spinat-Lachs-Pasta",
        "description": "Bandnudeln mit frischem Lachs, Blattspinat und einer leichten Zitronensahne.",
        "image_url": "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 520, "protein": 30, "carbs": 52, "fat": 20, "fiber": 3,
        "ingredients": [
            {"name": "Tagliatelle", "quantity": "400", "unit": "g"},
            {"name": "Lachsfilet", "quantity": "300", "unit": "g"},
            {"name": "Blattspinat", "quantity": "200", "unit": "g"},
            {"name": "Sahne", "quantity": "200", "unit": "ml"},
            {"name": "Zitrone", "quantity": "1", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Parmesan", "quantity": "40", "unit": "g"},
            {"name": "Olivenöl", "quantity": "1", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Tagliatelle nach Packungsanweisung kochen.",
            "Lachs in Wuerfel schneiden, in Olivenöl 3 Min anbraten. Herausnehmen.",
            "Knoblauch anschwitzen, Spinat zugeben und zusammenfallen lassen.",
            "Sahne und Zitronensaft einruehren, 3 Min einkochen.",
            "Lachs und abgetropfte Pasta in die Sauce geben, vorsichtig vermengen.",
            "Mit Parmesan, Salz und Pfeffer abschmecken. Sofort servieren.",
        ],
    },
    {
        "name": "Mac and Cheese mit Brokkoli",
        "description": "Cremige Kaesenudeln mit knackigem Brokkoli und knuspriger Kruste.",
        "image_url": "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 580, "protein": 24, "carbs": 55, "fat": 30, "fiber": 4,
        "ingredients": [
            {"name": "Makkaroni", "quantity": "350", "unit": "g"},
            {"name": "Brokkoli", "quantity": "300", "unit": "g"},
            {"name": "Cheddar", "quantity": "200", "unit": "g"},
            {"name": "Milch", "quantity": "300", "unit": "ml"},
            {"name": "Butter", "quantity": "30", "unit": "g"},
            {"name": "Mehl", "quantity": "2", "unit": "EL"},
            {"name": "Semmelbrösel", "quantity": "50", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Makkaroni al dente kochen, in den letzten 3 Min Brokkoliröschen mitkochen.",
            "Butter schmelzen, Mehl einruehren, Milch langsam zugiessen.",
            "Geriebenen Cheddar einschmelzen, mit Salz und Muskat wuerzen.",
            "Nudeln und Brokkoli unterruehren, in eine Auflaufform geben.",
            "Mit Semmelbrösel und etwas Butter bestreuen.",
            "Bei 200°C 15 Min ueberbacken bis die Kruste goldbraun ist.",
        ],
    },
    # ===================== VEGETARISCH =====================
    {
        "name": "Gemuese-Curry mit Kokosmilch",
        "description": "Aromatisches Thai-Curry mit buntem Gemuese und cremiger Kokosmilch.",
        "image_url": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 20, "servings": 4, "difficulty": "easy",
        "calories": 320, "protein": 8, "carbs": 28, "fat": 20, "fiber": 6,
        "ingredients": [
            {"name": "Kokosmilch", "quantity": "400", "unit": "ml"},
            {"name": "Rote Currypaste", "quantity": "2", "unit": "EL"},
            {"name": "Paprika rot", "quantity": "1", "unit": "Stueck"},
            {"name": "Zucchini", "quantity": "1", "unit": "Stueck"},
            {"name": "Aubergine", "quantity": "1", "unit": "Stueck"},
            {"name": "Kichererbsen (Dose)", "quantity": "1", "unit": "Dose"},
            {"name": "Babyspinat", "quantity": "100", "unit": "g"},
            {"name": "Ingwer", "quantity": "1", "unit": "EL"},
            {"name": "Sojasauce", "quantity": "2", "unit": "EL"},
            {"name": "Limette", "quantity": "1", "unit": "Stueck"},
            {"name": "Basmati-Reis", "quantity": "300", "unit": "g"},
        ],
        "instructions": [
            "Reis nach Packungsanweisung kochen.",
            "Gemuese in mundgerechte Stuecke schneiden.",
            "Currypaste mit etwas Kokosmilch in einem Wok anrösten.",
            "Restliche Kokosmilch, Ingwer und Sojasauce zugeben.",
            "Hartes Gemuese (Aubergine, Paprika) zuerst 5 Min kochen.",
            "Zucchini und Kichererbsen zugeben, weitere 5 Min kochen.",
            "Spinat unterheben, mit Limettensaft abschmecken.",
            "Mit Reis servieren.",
        ],
    },
    {
        "name": "Gefuellte Paprika mit Reis",
        "description": "Bunte Paprikaschoten gefuellt mit wuerzigem Reis, Gemuese und ueberbackenem Kaese.",
        "image_url": "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 35, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 14, "carbs": 48, "fat": 14, "fiber": 5,
        "ingredients": [
            {"name": "Paprika (bunt)", "quantity": "4", "unit": "Stueck"},
            {"name": "Reis", "quantity": "200", "unit": "g"},
            {"name": "Mais (Dose)", "quantity": "1", "unit": "Dose"},
            {"name": "Schwarze Bohnen (Dose)", "quantity": "1", "unit": "Dose"},
            {"name": "Tomatensosse", "quantity": "200", "unit": "ml"},
            {"name": "Kreuzkuemmel", "quantity": "1", "unit": "TL"},
            {"name": "Kaese gerieben", "quantity": "100", "unit": "g"},
            {"name": "Fruehlingszwiebeln", "quantity": "3", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Reis kochen und abkuehlen lassen.",
            "Paprika oben aufschneiden und entkernen.",
            "Reis mit Mais, Bohnen, Tomatensosse, Kreuzkuemmel und Salz mischen.",
            "Paprika mit der Mischung fuellen, in eine Auflaufform stellen.",
            "Etwas Wasser in die Form giessen (1cm hoch).",
            "Mit Kaese bestreuen und bei 180°C 30-35 Min backen.",
            "Mit Fruehlingszwiebeln garnieren.",
        ],
    },
    {
        "name": "Kartoffelgratin Dauphinois",
        "description": "Zart geschichtete Kartoffeln in cremiger Sahne mit goldbrauner Kruste.",
        "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 60, "servings": 6, "difficulty": "easy",
        "calories": 350, "protein": 10, "carbs": 35, "fat": 20, "fiber": 3,
        "ingredients": [
            {"name": "Kartoffeln (festkochend)", "quantity": "1", "unit": "kg"},
            {"name": "Sahne", "quantity": "300", "unit": "ml"},
            {"name": "Milch", "quantity": "200", "unit": "ml"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Gruyere", "quantity": "100", "unit": "g"},
            {"name": "Butter", "quantity": "20", "unit": "g"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 180°C vorheizen. Auflaufform mit Butter und Knoblauch ausreiben.",
            "Kartoffeln schaelen und in 3mm duenne Scheiben schneiden.",
            "Sahne mit Milch, Salz, Pfeffer und Muskatnuss verruehren.",
            "Kartoffelscheiben schuppenartig in die Form schichten.",
            "Sahne-Mischung gleichmaessig darueber giessen.",
            "Mit geriebenem Gruyere bestreuen.",
            "60 Min backen bis die Oberflaeche goldbraun und die Kartoffeln weich sind.",
        ],
    },
    {
        "name": "Blumenkohl-Wings (BBQ)",
        "description": "Knusprig panierte Blumenkohlröschen in rauchiger BBQ-Sauce — der perfekte Snack.",
        "image_url": "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 220, "protein": 6, "carbs": 32, "fat": 8, "fiber": 4,
        "ingredients": [
            {"name": "Blumenkohl", "quantity": "1", "unit": "Stueck"},
            {"name": "Mehl", "quantity": "100", "unit": "g"},
            {"name": "Wasser", "quantity": "120", "unit": "ml"},
            {"name": "Paprikapulver", "quantity": "1", "unit": "TL"},
            {"name": "Knoblauchpulver", "quantity": "1", "unit": "TL"},
            {"name": "BBQ-Sauce", "quantity": "150", "unit": "ml"},
            {"name": "Sesam", "quantity": "1", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Backofen auf 220°C vorheizen, Backblech mit Backpapier auslegen.",
            "Blumenkohl in grosse Röschen teilen.",
            "Mehl, Wasser, Paprika, Knoblauchpulver und Salz zu einem Teig verruehren.",
            "Röschen durch den Teig ziehen, auf das Blech setzen.",
            "15 Min backen bis sie anfangen knusprig zu werden.",
            "Aus dem Ofen nehmen, grosszuegig mit BBQ-Sauce bepinseln.",
            "Nochmal 10 Min backen. Mit Sesam bestreuen.",
        ],
    },
    {
        "name": "Mediterraner Ofengemuese-Salat",
        "description": "Geroestetes Ofengemuese mit Feta, Pinienkernen und Balsamico auf Rucola.",
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 30, "servings": 4, "difficulty": "easy",
        "calories": 290, "protein": 10, "carbs": 22, "fat": 18, "fiber": 5,
        "ingredients": [
            {"name": "Zucchini", "quantity": "2", "unit": "Stueck"},
            {"name": "Paprika rot", "quantity": "1", "unit": "Stueck"},
            {"name": "Aubergine", "quantity": "1", "unit": "Stueck"},
            {"name": "Kirschtomaten", "quantity": "200", "unit": "g"},
            {"name": "Rote Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Feta", "quantity": "150", "unit": "g"},
            {"name": "Rucola", "quantity": "100", "unit": "g"},
            {"name": "Pinienkerne", "quantity": "30", "unit": "g"},
            {"name": "Olivenöl", "quantity": "3", "unit": "EL"},
            {"name": "Balsamico", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Oregano", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Gemuese in grosse Stuecke schneiden, mit Olivenöl, Salz und Oregano mischen.",
            "Auf einem Backblech verteilen und 25-30 Min rösten.",
            "Pinienkerne in einer Pfanne ohne Fett anrösten.",
            "Rucola auf Tellern anrichten, Ofengemuese darauf verteilen.",
            "Feta darueber bröseln, Pinienkerne streuen, mit Balsamico betraeufeln.",
        ],
    },
    # ===================== SUPPEN & EINTOEPFE =====================
    {
        "name": "Cremige Kuerbissuppe",
        "description": "Samtig-cremige Kuerbissuppe mit Ingwer, Kokosmilch und geroestetem Kuerbiskernen.",
        "image_url": "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 240, "protein": 5, "carbs": 28, "fat": 12, "fiber": 4,
        "ingredients": [
            {"name": "Hokkaido-Kuerbis", "quantity": "1", "unit": "kg"},
            {"name": "Kartoffel", "quantity": "1", "unit": "Stueck"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Ingwer", "quantity": "1", "unit": "EL"},
            {"name": "Kokosmilch", "quantity": "200", "unit": "ml"},
            {"name": "Gemüsebrühe", "quantity": "600", "unit": "ml"},
            {"name": "Kuerbiskerne", "quantity": "30", "unit": "g"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Kuerbis entkernen und in Stuecke schneiden (Schale kann dran bleiben bei Hokkaido).",
            "Zwiebel und Ingwer in Olivenöl anschwitzen.",
            "Kuerbis und gewuerfelte Kartoffel zugeben, kurz mitbraten.",
            "Mit Gemüsebrühe ablöschen und 20 Min weich kochen.",
            "Kokosmilch zugeben und alles fein pueerieren.",
            "Mit Salz und Muskatnuss abschmecken.",
            "Kuerbiskerne in der Pfanne rösten und als Topping servieren.",
        ],
    },
    {
        "name": "Linsensuppe mit Wiener Wuerstchen",
        "description": "Herzhafte deutsche Linsensuppe mit Gemüse und Wiener Wuerstchen.",
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 35, "servings": 4, "difficulty": "easy",
        "calories": 420, "protein": 24, "carbs": 45, "fat": 14, "fiber": 12,
        "ingredients": [
            {"name": "Braune Linsen", "quantity": "300", "unit": "g"},
            {"name": "Wiener Wuerstchen", "quantity": "4", "unit": "Stueck"},
            {"name": "Karotten", "quantity": "2", "unit": "Stueck"},
            {"name": "Kartoffeln", "quantity": "2", "unit": "Stueck"},
            {"name": "Lauch", "quantity": "1", "unit": "Stange"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Essig", "quantity": "2", "unit": "EL"},
            {"name": "Lorbeerblatt", "quantity": "2", "unit": "Stueck"},
            {"name": "Gemüsebrühe", "quantity": "1", "unit": "l"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Linsen abspuelen. Gemuese in kleine Wuerfel schneiden.",
            "Zwiebel in etwas Öl anschwitzen, Karotten und Kartoffeln zugeben.",
            "Linsen und Gemüsebrühe zugiessen, Lorbeerblatt dazu.",
            "30 Min köcheln lassen bis Linsen weich sind.",
            "Wuerstchen in Scheiben schneiden, die letzten 5 Min mitkochen.",
            "Lorbeerblatt entfernen, mit Essig, Salz und Pfeffer abschmecken.",
        ],
    },
    {
        "name": "Thai-Kokossuppe (Tom Kha Gai)",
        "description": "Aromatische thailaendische Suppe mit Kokosmilch, Haehnchen und Galgant.",
        "image_url": "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 15, "servings": 4, "difficulty": "medium",
        "calories": 350, "protein": 22, "carbs": 12, "fat": 24, "fiber": 2,
        "ingredients": [
            {"name": "Haehnchenbrustfilet", "quantity": "400", "unit": "g"},
            {"name": "Kokosmilch", "quantity": "400", "unit": "ml"},
            {"name": "Huehnerbouillon", "quantity": "400", "unit": "ml"},
            {"name": "Champignons", "quantity": "200", "unit": "g"},
            {"name": "Kirschtomaten", "quantity": "150", "unit": "g"},
            {"name": "Zitronengras", "quantity": "2", "unit": "Stange"},
            {"name": "Ingwer", "quantity": "1", "unit": "EL"},
            {"name": "Limette", "quantity": "2", "unit": "Stueck"},
            {"name": "Fischsauce", "quantity": "2", "unit": "EL"},
            {"name": "Koriander", "quantity": "1", "unit": "Bund"},
            {"name": "Chili", "quantity": "1", "unit": "Stueck"},
        ],
        "instructions": [
            "Zitronengras klopfen und in Stuecke schneiden, Ingwer in Scheiben.",
            "Bouillon mit Kokosmilch, Zitronengras und Ingwer aufkochen.",
            "Haehnchen in Streifen schneiden, in die Suppe geben.",
            "Pilze und halbierte Tomaten zugeben, 10 Min köcheln.",
            "Mit Limettensaft und Fischsauce wuerzen.",
            "Zitronengras entfernen, mit Koriander und Chili garnieren.",
        ],
    },
    {
        "name": "Minestrone",
        "description": "Italienische Gemüsesuppe mit Nudeln, Bohnen und frischem Basilikum-Pesto.",
        "image_url": "https://images.unsplash.com/photo-1603105037880-880cd4f709d6?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 25, "servings": 6, "difficulty": "easy",
        "calories": 280, "protein": 12, "carbs": 38, "fat": 8, "fiber": 8,
        "ingredients": [
            {"name": "Karotten", "quantity": "2", "unit": "Stueck"},
            {"name": "Zucchini", "quantity": "1", "unit": "Stueck"},
            {"name": "Kartoffeln", "quantity": "2", "unit": "Stueck"},
            {"name": "Stangensellerie", "quantity": "2", "unit": "Stange"},
            {"name": "Weisse Bohnen (Dose)", "quantity": "1", "unit": "Dose"},
            {"name": "Passierte Tomaten", "quantity": "400", "unit": "ml"},
            {"name": "Kleine Nudeln (Ditalini)", "quantity": "100", "unit": "g"},
            {"name": "Gemüsebrühe", "quantity": "1", "unit": "l"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Basilikum-Pesto", "quantity": "2", "unit": "EL"},
            {"name": "Parmesan", "quantity": "40", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Alles Gemuese in kleine Wuerfel schneiden.",
            "Knoblauch und Sellerie in Olivenöl anschwitzen.",
            "Karotten und Kartoffeln zugeben, 3 Min mitbraten.",
            "Tomaten und Brühe zugiessen, 15 Min kochen.",
            "Nudeln, Zucchini und Bohnen zugeben, weitere 10 Min kochen.",
            "Mit Salz abschmecken. Mit Pesto und Parmesan servieren.",
        ],
    },
    {
        "name": "Brokkolisuppe mit Cheddar",
        "description": "Samtige Brokkolisuppe getoppt mit geschmolzenem Cheddar und Croutons.",
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 20, "servings": 4, "difficulty": "easy",
        "calories": 310, "protein": 16, "carbs": 18, "fat": 20, "fiber": 5,
        "ingredients": [
            {"name": "Brokkoli", "quantity": "600", "unit": "g"},
            {"name": "Kartoffel", "quantity": "1", "unit": "Stueck"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Cheddar", "quantity": "120", "unit": "g"},
            {"name": "Sahne", "quantity": "100", "unit": "ml"},
            {"name": "Gemüsebrühe", "quantity": "600", "unit": "ml"},
            {"name": "Butter", "quantity": "20", "unit": "g"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Zwiebel in Butter anschwitzen.",
            "Brokkoli und gewuerfelte Kartoffel zugeben.",
            "Mit Brühe ablöschen und 15 Min weich kochen.",
            "Sahne zugeben, fein pueerieren.",
            "2/3 des Cheddars einruehren bis geschmolzen.",
            "Mit Muskat, Salz und Pfeffer abschmecken.",
            "In Schalen fuellen und restlichen Cheddar darauf verteilen.",
        ],
    },
    # ===================== SALATE =====================
    {
        "name": "Caesar Salad mit Haehnchen",
        "description": "Knackiger Römersalat mit gegrilltem Haehnchen, Croutons und cremigem Caesar-Dressing.",
        "image_url": "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 10, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 28, "carbs": 18, "fat": 24, "fiber": 3,
        "ingredients": [
            {"name": "Römersalat", "quantity": "2", "unit": "Stueck"},
            {"name": "Haehnchenbrustfilet", "quantity": "400", "unit": "g"},
            {"name": "Parmesan", "quantity": "60", "unit": "g"},
            {"name": "Baguette", "quantity": "4", "unit": "Scheibe"},
            {"name": "Olivenöl", "quantity": "4", "unit": "EL"},
            {"name": "Knoblauch", "quantity": "1", "unit": "Zehe"},
            {"name": "Zitrone", "quantity": "1", "unit": "Stueck"},
            {"name": "Mayonnaise", "quantity": "3", "unit": "EL"},
            {"name": "Worcestersauce", "quantity": "1", "unit": "TL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Haehnchen salzen, pfeffern, in Olivenöl 5 Min pro Seite braten. In Streifen schneiden.",
            "Baguette in Wuerfel schneiden, mit Öl und Knoblauch in der Pfanne zu Croutons rösten.",
            "Dressing: Mayo, Zitronensaft, Worcestersauce, Olivenöl und geriebenen Parmesan verruehren.",
            "Salat waschen, in mundgerechte Stuecke reissen.",
            "Salat mit Dressing vermengen, Haehnchen und Croutons darauf verteilen.",
            "Mit Parmesan-Hobeln toppen.",
        ],
    },
    {
        "name": "Griechischer Bauernsalat",
        "description": "Klassischer Choriatiki-Salat mit Gurke, Tomate, Oliven und Feta.",
        "image_url": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 0, "servings": 4, "difficulty": "easy",
        "calories": 260, "protein": 10, "carbs": 12, "fat": 20, "fiber": 3,
        "ingredients": [
            {"name": "Tomaten", "quantity": "4", "unit": "Stueck"},
            {"name": "Gurke", "quantity": "1", "unit": "Stueck"},
            {"name": "Rote Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Paprika gruen", "quantity": "1", "unit": "Stueck"},
            {"name": "Kalamata-Oliven", "quantity": "100", "unit": "g"},
            {"name": "Feta", "quantity": "200", "unit": "g"},
            {"name": "Olivenöl", "quantity": "4", "unit": "EL"},
            {"name": "Oregano", "quantity": "1", "unit": "TL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Tomaten und Gurke in grosse Stuecke schneiden.",
            "Zwiebel in duenne Ringe schneiden, Paprika in Streifen.",
            "Alles in einer grossen Schüssel vermengen.",
            "Oliven darauf verteilen.",
            "Feta als ganzes Stueck obenauf legen.",
            "Grosszuegig mit Olivenöl betraeufeln und Oregano bestreuen.",
        ],
    },
    # ===================== FISCH & MEERESFRÜCHTE =====================
    {
        "name": "Gebratener Lachs mit Zitronen-Dill-Sauce",
        "description": "Knusprig gebratenes Lachsfilet mit einer leichten Zitronen-Dill-Sahnesauce.",
        "image_url": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 12, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 34, "carbs": 4, "fat": 24, "fiber": 0,
        "ingredients": [
            {"name": "Lachsfilet", "quantity": "4", "unit": "Stueck"},
            {"name": "Dill", "quantity": "1", "unit": "Bund"},
            {"name": "Zitrone", "quantity": "1", "unit": "Stueck"},
            {"name": "Sahne", "quantity": "150", "unit": "ml"},
            {"name": "Butter", "quantity": "20", "unit": "g"},
            {"name": "Weisswein", "quantity": "50", "unit": "ml"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Lachs salzen und pfeffern, mit der Hautseite zuerst in Butter 4 Min braten.",
            "Wenden und weitere 3 Min braten. Herausnehmen.",
            "In der Pfanne Weisswein einkochen, Sahne zugiessen.",
            "Zitronensaft und gehackten Dill einruehren.",
            "Sauce 3 Min einkochen lassen, mit Salz und Pfeffer abschmecken.",
            "Lachs mit Sauce servieren. Dazu passen Salzkartoffeln und Gurkensalat.",
        ],
    },
    {
        "name": "Garnelen-Spaghetti Aglio e Olio",
        "description": "Spaghetti mit Knoblauch, Chili und saftigen Garnelen — mediterran und schnell.",
        "image_url": "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 12, "servings": 4, "difficulty": "easy",
        "calories": 480, "protein": 24, "carbs": 58, "fat": 16, "fiber": 2,
        "ingredients": [
            {"name": "Spaghetti", "quantity": "400", "unit": "g"},
            {"name": "Riesengarnelen", "quantity": "300", "unit": "g"},
            {"name": "Knoblauch", "quantity": "4", "unit": "Zehe"},
            {"name": "Chiliflocken", "quantity": "1", "unit": "TL"},
            {"name": "Olivenöl", "quantity": "5", "unit": "EL"},
            {"name": "Petersilie", "quantity": "1", "unit": "Bund"},
            {"name": "Zitrone", "quantity": "1", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Spaghetti al dente kochen. 1 Tasse Nudelwasser aufheben.",
            "Knoblauch in duenne Scheiben schneiden.",
            "Olivenöl in einer Pfanne erhitzen, Knoblauch und Chili bei niedriger Hitze goldbraun braten.",
            "Garnelen zugeben, 2 Min pro Seite braten.",
            "Spaghetti und etwas Nudelwasser in die Pfanne geben, gut vermengen.",
            "Petersilie und Zitronensaft unterheben, sofort servieren.",
        ],
    },
    {
        "name": "Fischstäbchen selbstgemacht",
        "description": "Knusprige Fischstäbchen aus frischem Kabeljau — so viel besser als aus der Packung.",
        "image_url": "https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 340, "protein": 28, "carbs": 22, "fat": 16, "fiber": 1,
        "ingredients": [
            {"name": "Kabeljaufilet", "quantity": "500", "unit": "g"},
            {"name": "Semmelbrösel", "quantity": "150", "unit": "g"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Mehl", "quantity": "80", "unit": "g"},
            {"name": "Zitrone", "quantity": "1", "unit": "Stueck"},
            {"name": "Öl", "quantity": "4", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Kabeljau in Staebchen schneiden (ca. 2cm x 8cm), salzen und pfeffern.",
            "Drei Teller: Mehl, verquirlte Eier, Semmelbrösel.",
            "Fischstaebchen nacheinander panieren: Mehl, Ei, Brösel.",
            "In reichlich Öl bei mittlerer Hitze 3-4 Min pro Seite goldbraun braten.",
            "Auf Kuechenpapier abtropfen lassen.",
            "Mit Zitronenspalten und Remoulade servieren.",
        ],
    },
    # ===================== FRUEHSTUECK & BRUNCH =====================
    {
        "name": "Fluffige Pancakes",
        "description": "Extra-fluffige amerikanische Pancakes mit Ahornsirup und frischen Beeren.",
        "image_url": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 10, "carbs": 52, "fat": 14, "fiber": 2,
        "ingredients": [
            {"name": "Mehl", "quantity": "250", "unit": "g"},
            {"name": "Milch", "quantity": "300", "unit": "ml"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Backpulver", "quantity": "2", "unit": "TL"},
            {"name": "Zucker", "quantity": "2", "unit": "EL"},
            {"name": "Butter (geschmolzen)", "quantity": "40", "unit": "g"},
            {"name": "Vanilleextrakt", "quantity": "1", "unit": "TL"},
            {"name": "Ahornsirup", "quantity": "4", "unit": "EL"},
            {"name": "Blaubeeren", "quantity": "150", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Mehl, Backpulver, Zucker und Salz mischen.",
            "Milch, Eier, geschmolzene Butter und Vanille verquirlen.",
            "Fluessige Zutaten zu den trockenen geben und nur kurz verruehren (Klümpchen sind okay!).",
            "Pfanne bei mittlerer Hitze leicht einfetten.",
            "Pro Pancake ca. 60ml Teig in die Pfanne geben.",
            "Wenden wenn Blasen an der Oberfläche platzen (ca. 2 Min).",
            "Weitere 1-2 Min goldbraun backen.",
            "Gestapelt mit Ahornsirup und Blaubeeren servieren.",
        ],
    },
    {
        "name": "Shakshuka",
        "description": "Pochierte Eier in einer wuerzigen Tomaten-Paprika-Sauce — israelisches Pfannengericht.",
        "image_url": "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 20, "servings": 4, "difficulty": "easy",
        "calories": 280, "protein": 16, "carbs": 18, "fat": 16, "fiber": 4,
        "ingredients": [
            {"name": "Eier", "quantity": "6", "unit": "Stueck"},
            {"name": "Passierte Tomaten", "quantity": "400", "unit": "ml"},
            {"name": "Paprika rot", "quantity": "1", "unit": "Stueck"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Kreuzkuemmel", "quantity": "1", "unit": "TL"},
            {"name": "Paprikapulver", "quantity": "1", "unit": "TL"},
            {"name": "Chiliflocken", "quantity": "1", "unit": "Prise"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Petersilie", "quantity": "1", "unit": "Bund"},
            {"name": "Fladenbrot", "quantity": "4", "unit": "Stueck"},
        ],
        "instructions": [
            "Zwiebel und Paprika wuerfeln, in Olivenöl anschwitzen.",
            "Knoblauch, Kreuzkuemmel, Paprikapulver und Chili 1 Min mitrösten.",
            "Passierte Tomaten zugiessen, 10 Min einkochen lassen.",
            "Mit einem Löffel 6 Mulden formen und je ein Ei hineinschlagen.",
            "Deckel auflegen und 8-10 Min bei niedriger Hitze pochieren bis das Eiweiss fest ist.",
            "Mit Petersilie bestreuen und mit Fladenbrot servieren.",
        ],
    },
    {
        "name": "Avocado-Toast mit pochiertem Ei",
        "description": "Cremige Avocado auf knusprigem Sauerteigbrot mit perfekt pochiertem Ei.",
        "image_url": "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 5, "servings": 2, "difficulty": "medium",
        "calories": 320, "protein": 14, "carbs": 28, "fat": 18, "fiber": 6,
        "ingredients": [
            {"name": "Sauerteigbrot", "quantity": "2", "unit": "Scheibe"},
            {"name": "Avocado", "quantity": "1", "unit": "Stueck"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Zitrone", "quantity": "0.5", "unit": "Stueck"},
            {"name": "Chiliflocken", "quantity": "1", "unit": "Prise"},
            {"name": "Sesam", "quantity": "1", "unit": "TL"},
            {"name": "Salz", "quantity": "1", "unit": "Prise"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Wasser in einem Topf zum Simmern bringen (leichtes Blubbern, nicht kochen).",
            "Einen Schuss Essig ins Wasser geben, Strudel erzeugen, Ei hineingleiten lassen.",
            "3-4 Min pochieren, mit Schaumkelle herausheben.",
            "Brot toasten.",
            "Avocado mit Zitronensaft zerdrücken, salzen und pfeffern.",
            "Avocado auf Toast verteilen, pochiertes Ei daraufsetzen.",
            "Mit Chiliflocken und Sesam bestreuen.",
        ],
    },
    {
        "name": "Overnight Oats mit Beeren",
        "description": "Cremige Overnight Oats mit griechischem Joghurt, Chiasamen und frischen Beeren.",
        "image_url": "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&h=600&fit=crop",
        "prep_time": 5, "cook_time": 0, "servings": 2, "difficulty": "easy",
        "calories": 310, "protein": 14, "carbs": 42, "fat": 10, "fiber": 7,
        "ingredients": [
            {"name": "Haferflocken", "quantity": "100", "unit": "g"},
            {"name": "Griechischer Joghurt", "quantity": "150", "unit": "g"},
            {"name": "Milch", "quantity": "150", "unit": "ml"},
            {"name": "Chiasamen", "quantity": "1", "unit": "EL"},
            {"name": "Honig", "quantity": "1", "unit": "EL"},
            {"name": "Blaubeeren", "quantity": "80", "unit": "g"},
            {"name": "Himbeeren", "quantity": "80", "unit": "g"},
            {"name": "Mandeln", "quantity": "20", "unit": "g"},
        ],
        "instructions": [
            "Haferflocken, Joghurt, Milch, Chiasamen und Honig in einem Glas verruehren.",
            "Ueber Nacht (mindestens 6 Stunden) in den Kuehlschrank stellen.",
            "Am Morgen umruehren, bei Bedarf etwas Milch zugiessen.",
            "Mit frischen Beeren und gehackten Mandeln toppen.",
        ],
    },
    # ===================== SCHNELLE GERICHTE (UNTER 20 MIN) =====================
    {
        "name": "Gemuese-Quesadillas",
        "description": "Knusprige Tortillas gefuellt mit Gemuese, Bohnen und schmelzendem Kaese.",
        "image_url": "https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 8, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 16, "carbs": 38, "fat": 18, "fiber": 6,
        "ingredients": [
            {"name": "Tortillas (gross)", "quantity": "4", "unit": "Stueck"},
            {"name": "Paprika", "quantity": "1", "unit": "Stueck"},
            {"name": "Mais (Dose)", "quantity": "150", "unit": "g"},
            {"name": "Schwarze Bohnen (Dose)", "quantity": "150", "unit": "g"},
            {"name": "Kaese gerieben", "quantity": "200", "unit": "g"},
            {"name": "Jalapenos", "quantity": "2", "unit": "EL"},
            {"name": "Saure Sahne", "quantity": "4", "unit": "EL"},
            {"name": "Salsa", "quantity": "4", "unit": "EL"},
        ],
        "instructions": [
            "Paprika fein wuerfeln.",
            "Tortilla auf eine Haelfte mit Kaese, Paprika, Mais, Bohnen und Jalapenos belegen.",
            "Zuklappen und in einer heissen Pfanne ohne Fett 3-4 Min pro Seite braten.",
            "In Dreiecke schneiden und mit Saurer Sahne und Salsa servieren.",
        ],
    },
    {
        "name": "Bruschetta Classica",
        "description": "Knuspriges Röstbrot mit frischen Tomaten, Basilikum und Knoblauch.",
        "image_url": "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 5, "servings": 4, "difficulty": "easy",
        "calories": 220, "protein": 6, "carbs": 28, "fat": 10, "fiber": 2,
        "ingredients": [
            {"name": "Ciabatta", "quantity": "1", "unit": "Stueck"},
            {"name": "Tomaten (reif)", "quantity": "4", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Basilikum", "quantity": "1", "unit": "Bund"},
            {"name": "Olivenöl extra vergine", "quantity": "4", "unit": "EL"},
            {"name": "Balsamico", "quantity": "1", "unit": "EL"},
            {"name": "Meersalz", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Tomaten entkernen, wuerfeln und mit Basilikum, 2 EL Olivenöl, Balsamico und Salz mischen.",
            "15 Min ziehen lassen.",
            "Ciabatta in Scheiben schneiden und im Ofen oder auf dem Grill rösten.",
            "Warme Brotscheiben mit aufgeschnittener Knoblauchzehe einreiben.",
            "Mit restlichem Olivenöl betraeufeln.",
            "Tomatenmischung grosszuegig auf die Scheiben geben. Sofort servieren.",
        ],
    },
    {
        "name": "Wrap mit Haehnchen und Hummus",
        "description": "Vollkorn-Wrap mit gegrilltem Haehnchen, Hummus, Gemuese und frischer Minze.",
        "image_url": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 8, "servings": 4, "difficulty": "easy",
        "calories": 390, "protein": 28, "carbs": 36, "fat": 14, "fiber": 5,
        "ingredients": [
            {"name": "Vollkorn-Wraps", "quantity": "4", "unit": "Stueck"},
            {"name": "Haehnchenbrustfilet", "quantity": "400", "unit": "g"},
            {"name": "Hummus", "quantity": "200", "unit": "g"},
            {"name": "Gurke", "quantity": "1", "unit": "Stueck"},
            {"name": "Tomaten", "quantity": "2", "unit": "Stueck"},
            {"name": "Eisbergsalat", "quantity": "4", "unit": "Blatt"},
            {"name": "Rote Zwiebel", "quantity": "0.5", "unit": "Stueck"},
            {"name": "Minze", "quantity": "1", "unit": "Handvoll"},
            {"name": "Zitrone", "quantity": "0.5", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Haehnchen salzen, pfeffern, in der Pfanne 4 Min pro Seite braten. In Streifen schneiden.",
            "Gurke und Tomaten in Scheiben schneiden, Zwiebel in duenne Ringe.",
            "Wraps mit Hummus bestreichen.",
            "Salat, Gemuese und Haehnchen darauf verteilen.",
            "Minze und Zitronensaft darüber.",
            "Fest einrollen und diagonal halbieren.",
        ],
    },
    # ===================== BACKEN & DESSERTS =====================
    {
        "name": "Schokoladen-Lava-Kuchen",
        "description": "Warmer Schokoladenkuchen mit fluessigem Kern — das ultimative Dessert.",
        "image_url": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 12, "servings": 4, "difficulty": "medium",
        "calories": 420, "protein": 8, "carbs": 38, "fat": 28, "fiber": 2,
        "ingredients": [
            {"name": "Zartbitterschokolade", "quantity": "200", "unit": "g"},
            {"name": "Butter", "quantity": "100", "unit": "g"},
            {"name": "Eier", "quantity": "3", "unit": "Stueck"},
            {"name": "Zucker", "quantity": "80", "unit": "g"},
            {"name": "Mehl", "quantity": "50", "unit": "g"},
            {"name": "Kakaopulver", "quantity": "1", "unit": "EL"},
            {"name": "Vanilleextrakt", "quantity": "1", "unit": "TL"},
            {"name": "Salz", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen. 4 Foermchen einfetten und mit Kakao bestäuben.",
            "Schokolade und Butter im Wasserbad schmelzen.",
            "Eier mit Zucker schaumig schlagen.",
            "Geschmolzene Schokolade, Mehl und Vanille unter die Eimasse heben.",
            "Teig in die Foermchen fuellen (3/4 voll).",
            "Genau 12 Min backen — der Rand muss fest, die Mitte noch weich sein.",
            "1 Min warten, dann auf Teller stürzen. Sofort servieren.",
        ],
    },
    {
        "name": "Apfelkuchen mit Streusel",
        "description": "Saftiger Apfelkuchen mit buttrigen Streuseln — wie von Oma.",
        "image_url": "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=800&h=600&fit=crop",
        "prep_time": 25, "cook_time": 45, "servings": 12, "difficulty": "easy",
        "calories": 320, "protein": 4, "carbs": 42, "fat": 16, "fiber": 2,
        "ingredients": [
            {"name": "Aepfel (Boskoop)", "quantity": "5", "unit": "Stueck"},
            {"name": "Mehl", "quantity": "300", "unit": "g"},
            {"name": "Zucker", "quantity": "150", "unit": "g"},
            {"name": "Butter (kalt)", "quantity": "200", "unit": "g"},
            {"name": "Eier", "quantity": "1", "unit": "Stueck"},
            {"name": "Backpulver", "quantity": "1", "unit": "TL"},
            {"name": "Zimt", "quantity": "1", "unit": "TL"},
            {"name": "Zitrone", "quantity": "0.5", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Mehl, 100g Zucker, Ei, Backpulver und 130g kalte Butter zu einem Mürbeteig verkneten.",
            "2/3 des Teigs in eine Springform (26cm) druecken und einen Rand formen.",
            "Aepfel schaelen, vierteln, einschneiden und mit Zimt und Zitronensaft mischen.",
            "Aepfel auf dem Boden verteilen.",
            "Restlichen Teig mit 70g Butter und 50g Zucker zu Streuseln verarbeiten.",
            "Streusel ueber die Aepfel verteilen.",
            "Bei 180°C 40-45 Min goldbraun backen.",
        ],
    },
    {
        "name": "Tiramisu",
        "description": "Klassisches italienisches Tiramisu mit Mascarpone, Espresso und Kakao.",
        "image_url": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&h=600&fit=crop",
        "prep_time": 25, "cook_time": 0, "servings": 8, "difficulty": "medium",
        "calories": 380, "protein": 8, "carbs": 32, "fat": 24, "fiber": 1,
        "ingredients": [
            {"name": "Mascarpone", "quantity": "500", "unit": "g"},
            {"name": "Eigelb", "quantity": "4", "unit": "Stueck"},
            {"name": "Zucker", "quantity": "80", "unit": "g"},
            {"name": "Espresso (stark, abgekuehlt)", "quantity": "300", "unit": "ml"},
            {"name": "Löffelbiskuit", "quantity": "200", "unit": "g"},
            {"name": "Kakaopulver", "quantity": "2", "unit": "EL"},
            {"name": "Amaretto", "quantity": "2", "unit": "EL", "optional": True},
        ],
        "instructions": [
            "Eigelb mit Zucker cremig aufschlagen bis die Masse hell und dicklich ist.",
            "Mascarpone vorsichtig unterheben.",
            "Espresso mit Amaretto (optional) mischen.",
            "Löffelbiskuit kurz in den Espresso tauchen (nicht zu lange!) und in eine Form schichten.",
            "Haelfte der Mascarponecreme darauf verteilen.",
            "Zweite Schicht Löffelbiskuit und restliche Creme darauf geben.",
            "Mindestens 4 Stunden (besser ueber Nacht) kuehlen.",
            "Vor dem Servieren grosszuegig mit Kakaopulver bestäuben.",
        ],
    },
    {
        "name": "Bananenbrot",
        "description": "Saftiges Bananenbrot mit Walnuessen und einem Hauch Zimt — perfekt zum Kaffee.",
        "image_url": "https://images.unsplash.com/photo-1605090930601-64d5c7e4a5e6?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 55, "servings": 10, "difficulty": "easy",
        "calories": 260, "protein": 5, "carbs": 36, "fat": 12, "fiber": 2,
        "ingredients": [
            {"name": "Reife Bananen", "quantity": "3", "unit": "Stueck"},
            {"name": "Mehl", "quantity": "250", "unit": "g"},
            {"name": "Zucker", "quantity": "100", "unit": "g"},
            {"name": "Butter (geschmolzen)", "quantity": "80", "unit": "g"},
            {"name": "Ei", "quantity": "1", "unit": "Stueck"},
            {"name": "Backpulver", "quantity": "1", "unit": "TL"},
            {"name": "Natron", "quantity": "0.5", "unit": "TL"},
            {"name": "Zimt", "quantity": "1", "unit": "TL"},
            {"name": "Walnuesse", "quantity": "60", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 180°C vorheizen. Kastenform einfetten.",
            "Bananen mit einer Gabel zu Mus zerdrücken.",
            "Geschmolzene Butter und Zucker unterruehren, dann das Ei.",
            "Mehl, Backpulver, Natron, Zimt und Salz separat mischen.",
            "Trockene Zutaten zum Bananenmix geben und nur kurz verruehren.",
            "Gehackte Walnuesse unterheben.",
            "In die Form fuellen und 50-55 Min backen (Staebchenprobe!).",
            "10 Min in der Form abkuehlen, dann auf ein Gitter stürzen.",
        ],
    },
    # ===================== BEILAGEN =====================
    {
        "name": "Knusprige Rosmarinkartoffeln",
        "description": "Goldbraune Ofenkartoffeln mit frischem Rosmarin und Knoblauch.",
        "image_url": "https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 35, "servings": 4, "difficulty": "easy",
        "calories": 220, "protein": 4, "carbs": 32, "fat": 8, "fiber": 3,
        "ingredients": [
            {"name": "Kartoffeln (festkochend)", "quantity": "800", "unit": "g"},
            {"name": "Olivenöl", "quantity": "3", "unit": "EL"},
            {"name": "Rosmarin", "quantity": "3", "unit": "Stange"},
            {"name": "Knoblauch", "quantity": "4", "unit": "Zehe"},
            {"name": "Meersalz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Kartoffeln halbieren oder vierteln (ähnlich grosse Stuecke).",
            "Mit Olivenöl, Salz und Pfeffer mischen.",
            "Auf einem Backblech verteilen, Rosmarin und ungeschaelte Knoblauchzehen dazwischen legen.",
            "35 Min rösten, nach 20 Min einmal wenden.",
            "Knusprig und goldbraun servieren.",
        ],
    },
    {
        "name": "Cremiger Kartoffelpueree",
        "description": "Buttrig-cremiger Kartoffelpüree wie im Restaurant.",
        "image_url": "https://images.unsplash.com/photo-1600984575359-310ae7b6e7c2?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 20, "servings": 4, "difficulty": "easy",
        "calories": 260, "protein": 5, "carbs": 30, "fat": 14, "fiber": 2,
        "ingredients": [
            {"name": "Kartoffeln (mehlig)", "quantity": "1", "unit": "kg"},
            {"name": "Butter", "quantity": "80", "unit": "g"},
            {"name": "Milch (warm)", "quantity": "150", "unit": "ml"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Kartoffeln schaelen, in gleichgrosse Stuecke schneiden.",
            "In Salzwasser 15-18 Min weich kochen.",
            "Abgiessen und 2 Min ausdampfen lassen.",
            "Durch eine Kartoffelpresse druecken (nie mit Mixer!).",
            "Warme Milch und Butter unterruehren.",
            "Mit Muskat, Salz und Pfeffer abschmecken.",
        ],
    },
    # ===================== WEITERE HAUPTGERICHTE =====================
    {
        "name": "Flammkuchen Elsaesser Art",
        "description": "Duenner knuspriger Teig mit Schmand, Zwiebeln und Speck — wie im Elsass.",
        "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 14, "carbs": 38, "fat": 18, "fiber": 2,
        "ingredients": [
            {"name": "Mehl", "quantity": "250", "unit": "g"},
            {"name": "Wasser (warm)", "quantity": "125", "unit": "ml"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Schmand", "quantity": "200", "unit": "g"},
            {"name": "Creme fraiche", "quantity": "100", "unit": "g"},
            {"name": "Zwiebeln", "quantity": "2", "unit": "Stueck"},
            {"name": "Speckwuerfel", "quantity": "150", "unit": "g"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Mehl, Wasser, Öl und Salz zu einem glatten Teig kneten. 15 Min ruhen lassen.",
            "Backofen auf maximal (250°C+) vorheizen.",
            "Teig hauchdünn ausrollen auf ein bemehltes Backblech.",
            "Schmand mit Creme fraiche, Salz und Muskat verrühren, auf dem Teig verteilen.",
            "Duenne Zwiebelringe und Speckwuerfel darauf verteilen.",
            "10-12 Min backen bis der Rand knusprig und braun ist.",
        ],
    },
    {
        "name": "Suesssaure Haehnchenbrust Asia-Style",
        "description": "Knuspriges Haehnchen in einer fruchtigen suesssauren Sauce mit knackigem Gemuese.",
        "image_url": "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 420, "protein": 30, "carbs": 42, "fat": 14, "fiber": 3,
        "ingredients": [
            {"name": "Haehnchenbrustfilet", "quantity": "500", "unit": "g"},
            {"name": "Paprika (bunt)", "quantity": "2", "unit": "Stueck"},
            {"name": "Ananas (Dose)", "quantity": "200", "unit": "g"},
            {"name": "Speisestaerke", "quantity": "3", "unit": "EL"},
            {"name": "Ketchup", "quantity": "4", "unit": "EL"},
            {"name": "Sojasauce", "quantity": "2", "unit": "EL"},
            {"name": "Reisessig", "quantity": "2", "unit": "EL"},
            {"name": "Zucker", "quantity": "2", "unit": "EL"},
            {"name": "Ananassaft", "quantity": "100", "unit": "ml"},
            {"name": "Öl", "quantity": "3", "unit": "EL"},
            {"name": "Basmati-Reis", "quantity": "300", "unit": "g"},
        ],
        "instructions": [
            "Reis nach Packungsanweisung kochen.",
            "Haehnchen wuerfeln, in 2 EL Speisestaerke wenden.",
            "In heissem Öl goldbraun braten, herausnehmen.",
            "Paprika in Stuecke schneiden, im Wok 3 Min anbraten.",
            "Sauce: Ketchup, Soja, Essig, Zucker und Ananassaft verruehren.",
            "Sauce in den Wok giessen, aufkochen. Restliche Staerke mit etwas Wasser anruehren und zugeben.",
            "Haehnchen und Ananas unterruehren, 2 Min erwaermen.",
            "Mit Reis servieren.",
        ],
    },
    {
        "name": "Kartoffelpuffer mit Apfelmus",
        "description": "Goldbraune, knusprige Kartoffelpuffer — ein deutscher Klassiker mit Apfelmus.",
        "image_url": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 320, "protein": 7, "carbs": 40, "fat": 14, "fiber": 3,
        "ingredients": [
            {"name": "Kartoffeln (festkochend)", "quantity": "1", "unit": "kg"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Mehl", "quantity": "3", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Öl", "quantity": "4", "unit": "EL"},
            {"name": "Apfelmus", "quantity": "300", "unit": "g"},
        ],
        "instructions": [
            "Kartoffeln und Zwiebel grob reiben.",
            "In einem Tuch gut ausdruecken um Fluessigkeit zu entfernen.",
            "Mit Eiern, Mehl, Salz und Muskat mischen.",
            "Öl in einer Pfanne erhitzen.",
            "Löffelweise Teig in die Pfanne geben, flach druecken.",
            "Von jeder Seite 3-4 Min goldbraun braten.",
            "Auf Kuechenpapier abtropfen lassen, mit Apfelmus servieren.",
        ],
    },
    {
        "name": "Risotto mit Steinpilzen",
        "description": "Cremiges Risotto mit aromatischen Steinpilzen und Parmesan.",
        "image_url": "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 30, "servings": 4, "difficulty": "medium",
        "calories": 420, "protein": 12, "carbs": 58, "fat": 16, "fiber": 3,
        "ingredients": [
            {"name": "Risottoreis (Arborio)", "quantity": "300", "unit": "g"},
            {"name": "Steinpilze (getrocknet)", "quantity": "30", "unit": "g"},
            {"name": "Champignons", "quantity": "200", "unit": "g"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Weisswein", "quantity": "100", "unit": "ml"},
            {"name": "Gemüsebrühe (warm)", "quantity": "800", "unit": "ml"},
            {"name": "Parmesan", "quantity": "60", "unit": "g"},
            {"name": "Butter", "quantity": "40", "unit": "g"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Petersilie", "quantity": "1", "unit": "Bund"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Steinpilze 15 Min in warmem Wasser einweichen. Einweichwasser aufheben!",
            "Zwiebel fein wuerfeln, in Butter und Öl glasig anschwitzen.",
            "Reis zugeben, 2 Min mitrösten bis er glasig ist.",
            "Mit Weisswein ablöschen, einkochen lassen.",
            "Warme Brühe und Pilzwasser kellenweise zugeben, staendig ruehren.",
            "Frische Pilze in Scheiben schneiden, nach 15 Min zum Risotto geben.",
            "Nach 18-20 Min sollte der Reis cremig aber noch bissfest sein.",
            "Parmesan und restliche Butter einruehren, mit Petersilie servieren.",
        ],
    },
    {
        "name": "Pulled Chicken Burger",
        "description": "Zartes, geschreddertes Haehnchen in rauchiger BBQ-Sauce auf einem Brioche-Bun.",
        "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 480, "protein": 32, "carbs": 42, "fat": 18, "fiber": 2,
        "ingredients": [
            {"name": "Haehnchenbrustfilet", "quantity": "500", "unit": "g"},
            {"name": "BBQ-Sauce", "quantity": "150", "unit": "ml"},
            {"name": "Huehnerbouillon", "quantity": "100", "unit": "ml"},
            {"name": "Brioche-Buns", "quantity": "4", "unit": "Stueck"},
            {"name": "Krautsalat (Coleslaw)", "quantity": "200", "unit": "g"},
            {"name": "Paprikapulver geraeuchert", "quantity": "1", "unit": "TL"},
            {"name": "Knoblauchpulver", "quantity": "1", "unit": "TL"},
            {"name": "Zwiebelpulver", "quantity": "1", "unit": "TL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Haehnchen mit Gewuerzen einreiben.",
            "In einem Topf mit Bouillon und der Haelfte der BBQ-Sauce zugedeckt 20-25 Min sanft köcheln.",
            "Haehnchen mit zwei Gabeln zerreissen (pullen).",
            "Restliche BBQ-Sauce unterruehren.",
            "Brioche-Buns aufschneiden und kurz antoasten.",
            "Buns mit Pulled Chicken und Krautsalat belegen.",
        ],
    },
    {
        "name": "Ofen-Haehnchenschenkel mit Gemuese",
        "description": "Knusprige Haehnchenschenkel auf einem Bett aus Ofengemuese — alles auf einem Blech.",
        "image_url": "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 45, "servings": 4, "difficulty": "easy",
        "calories": 420, "protein": 34, "carbs": 22, "fat": 22, "fiber": 4,
        "ingredients": [
            {"name": "Haehnchenschenkel", "quantity": "4", "unit": "Stueck"},
            {"name": "Kartoffeln", "quantity": "500", "unit": "g"},
            {"name": "Paprika", "quantity": "2", "unit": "Stueck"},
            {"name": "Zucchini", "quantity": "1", "unit": "Stueck"},
            {"name": "Kirschtomaten", "quantity": "200", "unit": "g"},
            {"name": "Knoblauch", "quantity": "4", "unit": "Zehe"},
            {"name": "Olivenöl", "quantity": "3", "unit": "EL"},
            {"name": "Paprikapulver", "quantity": "1", "unit": "TL"},
            {"name": "Thymian", "quantity": "1", "unit": "TL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Kartoffeln in Spalten, Paprika und Zucchini in Stuecke schneiden.",
            "Gemuese mit Olivenöl, Thymian, Salz und Pfeffer auf einem Backblech verteilen.",
            "Haehnchenschenkel mit Paprikapulver, Salz und Pfeffer wuerzen.",
            "Auf das Gemuese setzen, Knoblauch und Tomaten dazwischen verteilen.",
            "45 Min backen bis die Haut goldbraun und knusprig ist.",
        ],
    },
    {
        "name": "Spaetzle selbstgemacht",
        "description": "Schwäbische Spaetzle aus frischem Teig — locker, zart und perfekt zu Braten.",
        "image_url": "https://images.unsplash.com/photo-1595295333158-4742f28fbd85?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 10, "servings": 4, "difficulty": "medium",
        "calories": 340, "protein": 12, "carbs": 52, "fat": 10, "fiber": 2,
        "ingredients": [
            {"name": "Mehl", "quantity": "400", "unit": "g"},
            {"name": "Eier", "quantity": "4", "unit": "Stueck"},
            {"name": "Wasser", "quantity": "150", "unit": "ml"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Butter", "quantity": "30", "unit": "g"},
        ],
        "instructions": [
            "Mehl, Eier, Wasser, Salz und Muskat zu einem zaehen Teig ruehren.",
            "Den Teig so lange schlagen bis er Blasen wirft.",
            "15 Min ruhen lassen.",
            "Einen grossen Topf Salzwasser zum Kochen bringen.",
            "Teig durch ein Spaetzlebrett oder -presse ins kochende Wasser schaben.",
            "Wenn die Spaetzle oben schwimmen (ca. 2 Min), mit einer Schaumkelle herausheben.",
            "In einer Pfanne mit Butter kurz schwenken und servieren.",
        ],
    },
    {
        "name": "Chili con Carne",
        "description": "Feurig-herzhaftes Chili mit Rinderhack, Bohnen und Paprika — Tex-Mex-Klassiker.",
        "image_url": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 40, "servings": 6, "difficulty": "easy",
        "calories": 420, "protein": 28, "carbs": 32, "fat": 18, "fiber": 10,
        "ingredients": [
            {"name": "Rinderhackfleisch", "quantity": "500", "unit": "g"},
            {"name": "Kidneybohnen (Dose)", "quantity": "1", "unit": "Dose"},
            {"name": "Mais (Dose)", "quantity": "1", "unit": "Dose"},
            {"name": "Passierte Tomaten", "quantity": "500", "unit": "ml"},
            {"name": "Paprika rot", "quantity": "1", "unit": "Stueck"},
            {"name": "Zwiebel", "quantity": "2", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "3", "unit": "Zehe"},
            {"name": "Kreuzkuemmel", "quantity": "2", "unit": "TL"},
            {"name": "Chilipulver", "quantity": "1", "unit": "TL"},
            {"name": "Oregano", "quantity": "1", "unit": "TL"},
            {"name": "Kakaopulver", "quantity": "1", "unit": "TL"},
            {"name": "Öl", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Saure Sahne", "quantity": "4", "unit": "EL"},
        ],
        "instructions": [
            "Zwiebeln und Knoblauch wuerfeln, in Öl anschwitzen.",
            "Hackfleisch zugeben und kruemelig anbraten.",
            "Alle Gewuerze (Kreuzkuemmel, Chili, Oregano, Kakao) 1 Min mitrösten.",
            "Passierte Tomaten und gewuerfelte Paprika zugiessen.",
            "30 Min bei niedriger Hitze köcheln.",
            "Kidneybohnen und Mais die letzten 10 Min mitkochen.",
            "Mit Salz abschmecken. Mit Saurer Sahne servieren.",
        ],
    },
    {
        "name": "Gemuese-Frittata",
        "description": "Italienisches Eiergericht mit buntem Gemuese — perfekt fuer Brunch oder schnelles Abendessen.",
        "image_url": "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 20, "servings": 4, "difficulty": "easy",
        "calories": 280, "protein": 18, "carbs": 10, "fat": 18, "fiber": 3,
        "ingredients": [
            {"name": "Eier", "quantity": "8", "unit": "Stueck"},
            {"name": "Zucchini", "quantity": "1", "unit": "Stueck"},
            {"name": "Kirschtomaten", "quantity": "150", "unit": "g"},
            {"name": "Paprika", "quantity": "1", "unit": "Stueck"},
            {"name": "Fruehlingszwiebeln", "quantity": "3", "unit": "Stueck"},
            {"name": "Feta", "quantity": "100", "unit": "g"},
            {"name": "Milch", "quantity": "50", "unit": "ml"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
            {"name": "Oregano", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Backofen auf 180°C vorheizen.",
            "Gemuese klein schneiden, in einer ofenfesten Pfanne in Olivenöl 5 Min anbraten.",
            "Eier mit Milch, Salz, Pfeffer und Oregano verquirlen.",
            "Eiermischung ueber das Gemuese giessen.",
            "Feta darueber bröseln.",
            "3 Min auf dem Herd stocken lassen, dann 15 Min im Ofen fertig backen.",
            "Goldbraun servieren, warm oder kalt.",
        ],
    },
    {
        "name": "Thailaendischer Glasnudelsalat",
        "description": "Erfrischender Glasnudelsalat mit Garnelen, Limette, Chili und frischen Kraeutern.",
        "image_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 5, "servings": 4, "difficulty": "easy",
        "calories": 280, "protein": 18, "carbs": 32, "fat": 8, "fiber": 2,
        "ingredients": [
            {"name": "Glasnudeln", "quantity": "200", "unit": "g"},
            {"name": "Garnelen", "quantity": "200", "unit": "g"},
            {"name": "Gurke", "quantity": "1", "unit": "Stueck"},
            {"name": "Karotte", "quantity": "1", "unit": "Stueck"},
            {"name": "Fruehlingszwiebeln", "quantity": "3", "unit": "Stueck"},
            {"name": "Koriander", "quantity": "1", "unit": "Bund"},
            {"name": "Limette", "quantity": "2", "unit": "Stueck"},
            {"name": "Fischsauce", "quantity": "2", "unit": "EL"},
            {"name": "Zucker", "quantity": "1", "unit": "EL"},
            {"name": "Chili", "quantity": "1", "unit": "Stueck"},
            {"name": "Erdnuesse", "quantity": "30", "unit": "g"},
        ],
        "instructions": [
            "Glasnudeln nach Packungsanweisung mit kochendem Wasser uebergiessen.",
            "Garnelen in heisser Pfanne 2 Min pro Seite braten.",
            "Gurke und Karotte in duenne Streifen schneiden.",
            "Dressing: Limettensaft, Fischsauce, Zucker und gehackten Chili verruehren.",
            "Alles in einer Schüssel vermengen.",
            "Mit Koriander und gehackten Erdnuessen toppen.",
        ],
    },
    {
        "name": "Bauernfrühstück",
        "description": "Deftige Bratkartoffeln mit Speck, Zwiebeln und Eiern — das klassische deutsche Pfannengericht.",
        "image_url": "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 420, "protein": 18, "carbs": 34, "fat": 24, "fiber": 3,
        "ingredients": [
            {"name": "Kartoffeln (vom Vortag)", "quantity": "800", "unit": "g"},
            {"name": "Speckwuerfel", "quantity": "150", "unit": "g"},
            {"name": "Zwiebel", "quantity": "2", "unit": "Stueck"},
            {"name": "Eier", "quantity": "4", "unit": "Stueck"},
            {"name": "Schnittlauch", "quantity": "1", "unit": "Bund"},
            {"name": "Butter", "quantity": "30", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Kartoffeln in Scheiben schneiden, Zwiebeln wuerfeln.",
            "Speck in einer grossen Pfanne knusprig braten.",
            "Butter und Kartoffeln zugeben, 15 Min braten bis sie goldbraun sind.",
            "Zwiebeln die letzten 5 Min mitbraten.",
            "Eier verquirlen, mit Salz und Pfeffer wuerzen.",
            "Eier ueber die Kartoffeln giessen, bei niedriger Hitze stocken lassen.",
            "Mit Schnittlauch bestreuen und direkt aus der Pfanne servieren.",
        ],
    },
    {
        "name": "Orientalische Linsen-Bowl",
        "description": "Bunte Buddha-Bowl mit Linsen, geröstetem Gemuese, Hummus und Tahini-Dressing.",
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 18, "carbs": 48, "fat": 14, "fiber": 12,
        "ingredients": [
            {"name": "Rote Linsen", "quantity": "200", "unit": "g"},
            {"name": "Suesskartoffel", "quantity": "1", "unit": "Stueck"},
            {"name": "Kichererbsen (Dose)", "quantity": "1", "unit": "Dose"},
            {"name": "Babyspinat", "quantity": "100", "unit": "g"},
            {"name": "Avocado", "quantity": "1", "unit": "Stueck"},
            {"name": "Hummus", "quantity": "4", "unit": "EL"},
            {"name": "Tahini", "quantity": "2", "unit": "EL"},
            {"name": "Zitrone", "quantity": "1", "unit": "Stueck"},
            {"name": "Kreuzkuemmel", "quantity": "1", "unit": "TL"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Suesskartoffel wuerfeln, Kichererbsen abtropfen, beides mit Olivenöl und Kreuzkuemmel auf einem Blech bei 200°C 20 Min rösten.",
            "Rote Linsen in 10 Min weich kochen, abgiessen.",
            "Tahini-Dressing: Tahini, Zitronensaft, 2 EL Wasser und Salz verruehren.",
            "Bowls anrichten: Spinat, Linsen, Ofengemuese, Avocado-Scheiben.",
            "Hummus und Tahini-Dressing darauf verteilen.",
        ],
    },
    {
        "name": "Ratatouille",
        "description": "Provenzalisches Gemuesegericht mit Aubergine, Zucchini, Paprika und Tomaten.",
        "image_url": "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 40, "servings": 4, "difficulty": "easy",
        "calories": 180, "protein": 4, "carbs": 18, "fat": 10, "fiber": 6,
        "ingredients": [
            {"name": "Aubergine", "quantity": "1", "unit": "Stueck"},
            {"name": "Zucchini", "quantity": "2", "unit": "Stueck"},
            {"name": "Paprika rot", "quantity": "1", "unit": "Stueck"},
            {"name": "Paprika gelb", "quantity": "1", "unit": "Stueck"},
            {"name": "Tomaten", "quantity": "4", "unit": "Stueck"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "3", "unit": "Zehe"},
            {"name": "Olivenöl", "quantity": "4", "unit": "EL"},
            {"name": "Herbes de Provence", "quantity": "1", "unit": "EL"},
            {"name": "Tomatenmark", "quantity": "1", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Basilikum", "quantity": "1", "unit": "Bund"},
        ],
        "instructions": [
            "Alles Gemuese in gleichgrosse Wuerfel (2cm) schneiden.",
            "Zwiebel und Knoblauch in Olivenöl anschwitzen.",
            "Aubergine zugeben, 5 Min anbraten.",
            "Paprika und Zucchini zugeben, weitere 5 Min braten.",
            "Tomaten und Tomatenmark unterruehren.",
            "Herbes de Provence und Salz zugeben, zugedeckt 25 Min schmoren.",
            "Mit frischem Basilikum servieren. Dazu passt Baguette.",
        ],
    },
    {
        "name": "Koenigsberger Klopse",
        "description": "Zarte Fleischklopse in weisser Kapernsosse — ostpreussischer Klassiker.",
        "image_url": "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=800&h=600&fit=crop",
        "prep_time": 25, "cook_time": 20, "servings": 4, "difficulty": "medium",
        "calories": 420, "protein": 28, "carbs": 22, "fat": 24, "fiber": 1,
        "ingredients": [
            {"name": "Rinderhackfleisch", "quantity": "300", "unit": "g"},
            {"name": "Schweinehackfleisch", "quantity": "200", "unit": "g"},
            {"name": "Brötchen (altbacken)", "quantity": "1", "unit": "Stueck"},
            {"name": "Ei", "quantity": "1", "unit": "Stueck"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Kapern", "quantity": "3", "unit": "EL"},
            {"name": "Fleischbrühe", "quantity": "600", "unit": "ml"},
            {"name": "Sahne", "quantity": "200", "unit": "ml"},
            {"name": "Butter", "quantity": "30", "unit": "g"},
            {"name": "Mehl", "quantity": "2", "unit": "EL"},
            {"name": "Zitrone", "quantity": "1", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Brötchen einweichen und ausdrücken. Zwiebel fein wuerfeln.",
            "Hack mit Brötchen, Ei, Zwiebel, Salz und Pfeffer verkneten.",
            "Mit nassen Haenden gleichmaessige Klopse formen.",
            "Fleischbrühe aufkochen, Klopse hineingeben und 15 Min ziehen lassen (nicht kochen!).",
            "Klopse herausnehmen. Butter schmelzen, Mehl einruehren.",
            "Mit Brühe ablöschen, Sahne zugiessen, glattruehren.",
            "Kapern und Zitronensaft einruehren, Klopse zurueck in die Sauce geben.",
            "Mit Salzkartoffeln oder Reis servieren.",
        ],
    },
    {
        "name": "Zucchini-Puffer mit Tzatziki",
        "description": "Leichte, knusprige Zucchini-Puffer mit frischem Tzatziki-Dip.",
        "image_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 10, "servings": 4, "difficulty": "easy",
        "calories": 240, "protein": 10, "carbs": 20, "fat": 14, "fiber": 2,
        "ingredients": [
            {"name": "Zucchini", "quantity": "2", "unit": "Stueck"},
            {"name": "Feta", "quantity": "100", "unit": "g"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Mehl", "quantity": "4", "unit": "EL"},
            {"name": "Dill", "quantity": "1", "unit": "Bund"},
            {"name": "Griechischer Joghurt", "quantity": "200", "unit": "g"},
            {"name": "Gurke", "quantity": "0.5", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "1", "unit": "Zehe"},
            {"name": "Olivenöl", "quantity": "3", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Zucchini grob reiben, mit Salz 10 Min ziehen lassen, dann gut ausdruecken.",
            "Mit zerbröseltem Feta, Eiern, Mehl und gehacktem Dill mischen.",
            "Tzatziki: Gurke reiben, ausdruecken, mit Joghurt, Knoblauch und Salz mischen.",
            "Olivenöl in einer Pfanne erhitzen.",
            "Löffelweise Zucchinimasse in die Pfanne geben, flach druecken.",
            "3 Min pro Seite goldbraun braten.",
            "Mit Tzatziki servieren.",
        ],
    },
    # ===================== WEITERE REZEPTE BIS 50 =====================
    {
        "name": "Tomatensuppe mit Grilled Cheese",
        "description": "Samtige Tomatensuppe serviert mit goldenem Grilled-Cheese-Sandwich zum Dippen.",
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 420, "protein": 14, "carbs": 38, "fat": 24, "fiber": 4,
        "ingredients": [
            {"name": "Passierte Tomaten", "quantity": "800", "unit": "ml"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Gemüsebrühe", "quantity": "200", "unit": "ml"},
            {"name": "Sahne", "quantity": "100", "unit": "ml"},
            {"name": "Basilikum", "quantity": "1", "unit": "Bund"},
            {"name": "Toastbrot", "quantity": "8", "unit": "Scheibe"},
            {"name": "Cheddar", "quantity": "200", "unit": "g"},
            {"name": "Butter", "quantity": "40", "unit": "g"},
            {"name": "Olivenöl", "quantity": "2", "unit": "EL"},
            {"name": "Zucker", "quantity": "1", "unit": "TL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Zwiebel und Knoblauch in Olivenöl anschwitzen.",
            "Passierte Tomaten und Brühe zugiessen, 15 Min köcheln.",
            "Sahne und Basilikum zugeben, pueerieren.",
            "Mit Zucker, Salz und Pfeffer abschmecken.",
            "Fuer Grilled Cheese: Toastscheiben buttern, Cheddar dazwischen legen.",
            "In der Pfanne von jeder Seite 3 Min goldbraun braten.",
            "Diagonal halbieren und zur Suppe servieren.",
        ],
    },
]

def main():
    print(f"Inserting {len(RECIPES)} recipes into Supabase...")

    success = 0
    errors = 0

    for i, recipe in enumerate(RECIPES):
        try:
            recipe_id = insert_recipe(recipe)
            success += 1
            print(f"  [{i+1}/{len(RECIPES)}] {recipe['name']} -> {recipe_id}")
        except Exception as e:
            errors += 1
            print(f"  [{i+1}/{len(RECIPES)}] ERROR: {recipe['name']} -> {e}")

    print(f"\nDone! {success} success, {errors} errors.")


if __name__ == "__main__":
    main()
