"""
Seed batch 2: 46 more recipes into Supabase.
Run with: python seed_recipes_2.py
"""

import os
from dotenv import load_dotenv
load_dotenv()

from supabase import create_client

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)


def insert_recipe(r):
    result = supabase.table("recipes").insert({
        "name": r["name"], "description": r["description"], "image_url": r["image_url"],
        "prep_time": r["prep_time"], "cook_time": r["cook_time"], "servings": r["servings"],
        "difficulty": r["difficulty"], "calories": r.get("calories"), "protein": r.get("protein"),
        "carbs": r.get("carbs"), "fat": r.get("fat"), "fiber": r.get("fiber"),
    }).execute()
    rid = result.data[0]["id"]
    for i, ing in enumerate(r["ingredients"]):
        supabase.table("recipe_ingredients").insert({
            "recipe_id": rid, "ingredient_name": ing["name"], "quantity": str(ing["quantity"]),
            "unit": ing["unit"], "is_optional": ing.get("optional", False), "ingredient_order": i+1,
        }).execute()
    for i, step in enumerate(r["instructions"]):
        supabase.table("recipe_instructions").insert({
            "recipe_id": rid, "step_number": i+1, "instruction": step,
        }).execute()
    return rid


RECIPES = [
    {
        "name": "Gyros-Teller mit Tzatziki",
        "description": "Wuerziges Gyros-Fleisch mit frischem Tzatziki, Krautsalat und Fladenbrot.",
        "image_url": "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 450, "protein": 32, "carbs": 28, "fat": 22, "fiber": 3,
        "ingredients": [
            {"name": "Schweinefleisch (Nacken)", "quantity": "600", "unit": "g"},
            {"name": "Gyros-Gewuerz", "quantity": "2", "unit": "EL"},
            {"name": "Griechischer Joghurt", "quantity": "300", "unit": "g"},
            {"name": "Gurke", "quantity": "1", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Fladenbrot", "quantity": "4", "unit": "Stueck"},
            {"name": "Olivenoel", "quantity": "2", "unit": "EL"},
            {"name": "Zitrone", "quantity": "0.5", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Fleisch in duenne Streifen schneiden, mit Gyros-Gewuerz und Olivenoel marinieren.",
            "Mindestens 30 Min (besser ueber Nacht) ziehen lassen.",
            "Tzatziki: Gurke reiben, ausdruecken, mit Joghurt, Knoblauch und Zitronensaft mischen.",
            "Fleisch in einer heissen Pfanne portionsweise scharf anbraten.",
            "Fladenbrot kurz erwaermen.",
            "Alles zusammen auf Tellern anrichten.",
        ],
    },
    {
        "name": "Pilzrisotto mit Trueffeloel",
        "description": "Luxurioeses Pilzrisotto verfeinert mit einem Hauch Trueffeloel und Parmesan.",
        "image_url": "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "medium",
        "calories": 400, "protein": 10, "carbs": 54, "fat": 16, "fiber": 3,
        "ingredients": [
            {"name": "Risottoreis", "quantity": "300", "unit": "g"},
            {"name": "Mischpilze", "quantity": "400", "unit": "g"},
            {"name": "Schalotte", "quantity": "2", "unit": "Stueck"},
            {"name": "Weisswein", "quantity": "100", "unit": "ml"},
            {"name": "Gemuese bruehe", "quantity": "800", "unit": "ml"},
            {"name": "Parmesan", "quantity": "60", "unit": "g"},
            {"name": "Butter", "quantity": "40", "unit": "g"},
            {"name": "Trueffeloel", "quantity": "1", "unit": "TL"},
            {"name": "Thymian", "quantity": "1", "unit": "TL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Pilze putzen und in Stuecke schneiden, Schalotten fein wuerfeln.",
            "Schalotten in Butter glasig anschwitzen, Reis zugeben und 2 Min mitroesten.",
            "Mit Weisswein abloeschen.",
            "Warme Bruehe kellenweise zugeben, staendig ruehren.",
            "Pilze separat in Butter anbraten, nach 15 Min zum Risotto geben.",
            "Nach 20 Min Parmesan einruehren.",
            "Mit Trueffeloel betraeufeln und sofort servieren.",
        ],
    },
    {
        "name": "Spaghetti Bolognese",
        "description": "Die perfekte Bolognese — langsam geschmort mit Soffritto, Rotwein und Tomaten.",
        "image_url": "https://images.unsplash.com/photo-1622973536968-3ead9e780960?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 60, "servings": 6, "difficulty": "easy",
        "calories": 520, "protein": 26, "carbs": 56, "fat": 20, "fiber": 4,
        "ingredients": [
            {"name": "Spaghetti", "quantity": "500", "unit": "g"},
            {"name": "Rinderhackfleisch", "quantity": "500", "unit": "g"},
            {"name": "Passierte Tomaten", "quantity": "500", "unit": "ml"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Karotte", "quantity": "1", "unit": "Stueck"},
            {"name": "Sellerie", "quantity": "1", "unit": "Stange"},
            {"name": "Rotwein", "quantity": "100", "unit": "ml"},
            {"name": "Tomatenmark", "quantity": "2", "unit": "EL"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Olivenoel", "quantity": "2", "unit": "EL"},
            {"name": "Oregano", "quantity": "1", "unit": "TL"},
            {"name": "Parmesan", "quantity": "50", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Zwiebel, Karotte und Sellerie fein wuerfeln (Soffritto).",
            "In Olivenoel 8 Min sanft anschwitzen.",
            "Hackfleisch zugeben, kruemelig anbraten.",
            "Tomatenmark kurz mitroesten, mit Rotwein abloeschen.",
            "Passierte Tomaten, Knoblauch und Oregano zugeben.",
            "50-60 Min bei niedriger Hitze koecheln lassen.",
            "Spaghetti al dente kochen, mit Sauce und Parmesan servieren.",
        ],
    },
    {
        "name": "Gemuesepfanne mit Tofu",
        "description": "Knuspriger Tofu mit buntem Wokgemuese in einer wuerzigen Sojasauce.",
        "image_url": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 12, "servings": 4, "difficulty": "easy",
        "calories": 280, "protein": 16, "carbs": 22, "fat": 14, "fiber": 5,
        "ingredients": [
            {"name": "Tofu (fest)", "quantity": "400", "unit": "g"},
            {"name": "Brokkoli", "quantity": "200", "unit": "g"},
            {"name": "Paprika rot", "quantity": "1", "unit": "Stueck"},
            {"name": "Karotte", "quantity": "1", "unit": "Stueck"},
            {"name": "Zuckerschoten", "quantity": "100", "unit": "g"},
            {"name": "Sojasauce", "quantity": "3", "unit": "EL"},
            {"name": "Sesamoel", "quantity": "1", "unit": "EL"},
            {"name": "Ingwer", "quantity": "1", "unit": "EL"},
            {"name": "Speisestaerke", "quantity": "2", "unit": "EL"},
            {"name": "Sesam", "quantity": "1", "unit": "EL"},
        ],
        "instructions": [
            "Tofu in Wuerfel schneiden, trocken tupfen, in Speisestaerke wenden.",
            "In heissem Oel goldbraun braten, herausnehmen.",
            "Gemuese in mundgerechte Stuecke schneiden.",
            "Im Wok bei starker Hitze 5 Min braten.",
            "Sojasauce, Sesamoel und Ingwer zufuegen.",
            "Tofu zurueck, 2 Min erwaermen, mit Sesam bestreuen.",
        ],
    },
    {
        "name": "Lachs im Blätterteig",
        "description": "Saftiger Lachs in einer Blaetterteighuelle mit Spinat und Frischkaese.",
        "image_url": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 25, "servings": 4, "difficulty": "medium",
        "calories": 520, "protein": 30, "carbs": 28, "fat": 32, "fiber": 2,
        "ingredients": [
            {"name": "Lachsfilet", "quantity": "4", "unit": "Stueck"},
            {"name": "Blaetterteig", "quantity": "2", "unit": "Packung"},
            {"name": "Blattspinat", "quantity": "150", "unit": "g"},
            {"name": "Frischkaese", "quantity": "100", "unit": "g"},
            {"name": "Dill", "quantity": "1", "unit": "Bund"},
            {"name": "Eigelb", "quantity": "1", "unit": "Stueck"},
            {"name": "Zitrone", "quantity": "0.5", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Spinat kurz zusammenfallen lassen, abkuehlen und ausdruecken.",
            "Frischkaese mit Dill, Zitronensaft, Salz und Pfeffer mischen.",
            "Blaetterteig ausrollen, Lachs darauf legen.",
            "Spinat und Frischkaese auf den Lachs geben.",
            "Blaetterteig verschliessen, mit Eigelb bestreichen.",
            "Bei 200°C 20-25 Min goldbraun backen.",
        ],
    },
    {
        "name": "Griechische Moussaka",
        "description": "Geschichteter Auflauf mit Auberginen, Hackfleisch und cremiger Bechamel.",
        "image_url": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&h=600&fit=crop",
        "prep_time": 30, "cook_time": 45, "servings": 6, "difficulty": "medium",
        "calories": 460, "protein": 24, "carbs": 28, "fat": 28, "fiber": 4,
        "ingredients": [
            {"name": "Auberginen", "quantity": "3", "unit": "Stueck"},
            {"name": "Lammhackfleisch", "quantity": "500", "unit": "g"},
            {"name": "Passierte Tomaten", "quantity": "400", "unit": "ml"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Zimt", "quantity": "0.5", "unit": "TL"},
            {"name": "Milch", "quantity": "400", "unit": "ml"},
            {"name": "Butter", "quantity": "40", "unit": "g"},
            {"name": "Mehl", "quantity": "40", "unit": "g"},
            {"name": "Ei", "quantity": "1", "unit": "Stueck"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Olivenoel", "quantity": "4", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Auberginen in Scheiben schneiden, salzen, 15 Min ziehen lassen, abtupfen.",
            "Auberginen in Olivenoel von beiden Seiten anbraten.",
            "Hackfleisch mit Zwiebel und Knoblauch anbraten, mit Tomaten und Zimt 15 Min koecheln.",
            "Bechamel: Butter, Mehl, Milch verruehren, mit Muskat wuerzen. Vom Herd, Ei einruehren.",
            "Auflaufform schichten: Auberginen, Hack, Auberginen, Hack.",
            "Bechamel darueber giessen.",
            "Bei 180°C 40-45 Min goldbraun ueberbacken.",
        ],
    },
    {
        "name": "Butter Chicken",
        "description": "Zartes Haehnchen in einer cremigen Tomaten-Butter-Sauce — indischer Klassiker.",
        "image_url": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 30, "servings": 4, "difficulty": "medium",
        "calories": 420, "protein": 32, "carbs": 14, "fat": 26, "fiber": 3,
        "ingredients": [
            {"name": "Haehnchenbrustfilet", "quantity": "600", "unit": "g"},
            {"name": "Joghurt", "quantity": "100", "unit": "g"},
            {"name": "Passierte Tomaten", "quantity": "400", "unit": "ml"},
            {"name": "Sahne", "quantity": "100", "unit": "ml"},
            {"name": "Butter", "quantity": "50", "unit": "g"},
            {"name": "Garam Masala", "quantity": "2", "unit": "TL"},
            {"name": "Kurkuma", "quantity": "1", "unit": "TL"},
            {"name": "Kreuzkuemmel", "quantity": "1", "unit": "TL"},
            {"name": "Chilipulver", "quantity": "0.5", "unit": "TL"},
            {"name": "Ingwer", "quantity": "1", "unit": "EL"},
            {"name": "Knoblauch", "quantity": "3", "unit": "Zehe"},
            {"name": "Basmati-Reis", "quantity": "300", "unit": "g"},
            {"name": "Koriander", "quantity": "1", "unit": "Bund"},
        ],
        "instructions": [
            "Haehnchen wuerfeln, mit Joghurt, Kurkuma und Garam Masala marinieren (30 Min).",
            "Reis kochen.",
            "Haehnchen in Butter anbraten, herausnehmen.",
            "Ingwer und Knoblauch anschwitzen, restliche Gewuerze 1 Min mitroesten.",
            "Passierte Tomaten zugiessen, 15 Min koecheln.",
            "Sahne und Haehnchen zurueck, 5 Min erwaermen.",
            "Mit Koriander und Reis servieren.",
        ],
    },
    {
        "name": "Gnocchi mit Salbei-Butter",
        "description": "Selbstgemachte Gnocchi in nussbrauner Salbeibutter mit Parmesan.",
        "image_url": "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&h=600&fit=crop",
        "prep_time": 40, "cook_time": 10, "servings": 4, "difficulty": "medium",
        "calories": 380, "protein": 10, "carbs": 48, "fat": 16, "fiber": 3,
        "ingredients": [
            {"name": "Kartoffeln (mehlig)", "quantity": "1", "unit": "kg"},
            {"name": "Mehl", "quantity": "200", "unit": "g"},
            {"name": "Eigelb", "quantity": "1", "unit": "Stueck"},
            {"name": "Butter", "quantity": "80", "unit": "g"},
            {"name": "Salbei", "quantity": "1", "unit": "Bund"},
            {"name": "Parmesan", "quantity": "50", "unit": "g"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Kartoffeln mit Schale 25 Min kochen, schaelen, durch die Presse druecken.",
            "Mit Mehl, Eigelb, Muskat und Salz zu einem geschmeidigen Teig kneten.",
            "Rollen formen, in 2cm Stuecke schneiden, mit einer Gabel eindrücken.",
            "In kochendem Salzwasser garen bis sie aufschwimmen (2-3 Min).",
            "Butter in einer Pfanne schmelzen lassen bis sie nussbraun wird.",
            "Salbeiblaetter darin knusprig braten.",
            "Gnocchi in der Salbeibutter schwenken, mit Parmesan servieren.",
        ],
    },
    {
        "name": "Tortilla Espanola",
        "description": "Spanisches Kartoffel-Omelette — aussen goldbraun, innen saftig-cremig.",
        "image_url": "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 30, "servings": 6, "difficulty": "easy",
        "calories": 280, "protein": 12, "carbs": 22, "fat": 16, "fiber": 2,
        "ingredients": [
            {"name": "Kartoffeln", "quantity": "600", "unit": "g"},
            {"name": "Eier", "quantity": "6", "unit": "Stueck"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Olivenoel", "quantity": "100", "unit": "ml"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Kartoffeln schaelen, in duenne Scheiben schneiden.",
            "In reichlich Olivenoel bei mittlerer Hitze 15 Min weich fritieren.",
            "Zwiebel in Ringen die letzten 5 Min mitgaren.",
            "Eier verquirlen, salzen, Kartoffeln unterheben.",
            "In einer beschichteten Pfanne bei niedriger Hitze 8 Min stocken lassen.",
            "Auf einen Teller stuerzen, zurueck in die Pfanne gleiten lassen, weitere 5 Min.",
            "Lauwarm in Stuecken servieren.",
        ],
    },
    {
        "name": "Sushi-Bowl (Poke Bowl)",
        "description": "Deconstructed Sushi als Bowl mit Lachs, Avocado, Edamame und Sushi-Reis.",
        "image_url": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 420, "protein": 26, "carbs": 48, "fat": 14, "fiber": 4,
        "ingredients": [
            {"name": "Sushi-Reis", "quantity": "300", "unit": "g"},
            {"name": "Lachsfilet (Sashimi-Qualitaet)", "quantity": "300", "unit": "g"},
            {"name": "Avocado", "quantity": "1", "unit": "Stueck"},
            {"name": "Edamame", "quantity": "100", "unit": "g"},
            {"name": "Gurke", "quantity": "1", "unit": "Stueck"},
            {"name": "Karotte", "quantity": "1", "unit": "Stueck"},
            {"name": "Sojasauce", "quantity": "3", "unit": "EL"},
            {"name": "Reisessig", "quantity": "2", "unit": "EL"},
            {"name": "Sesam", "quantity": "1", "unit": "EL"},
            {"name": "Nori-Blaetter", "quantity": "2", "unit": "Stueck"},
        ],
        "instructions": [
            "Sushi-Reis kochen, mit Reisessig wuerzen, abkuehlen lassen.",
            "Lachs in Wuerfel schneiden, mit 1 EL Sojasauce marinieren.",
            "Avocado und Gurke in Scheiben, Karotte in duenne Streifen schneiden.",
            "Reis in Bowls verteilen.",
            "Lachs, Avocado, Gurke, Karotte und Edamame darauf anrichten.",
            "Mit Sojasauce, Sesam und zerbroeselten Nori-Blaettern toppen.",
        ],
    },
    {
        "name": "Zitronenhaehnchen vom Blech",
        "description": "Mediterranes Zitronenhaehnchen mit Oliven und Kartoffeln — alles auf einem Blech.",
        "image_url": "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 50, "servings": 4, "difficulty": "easy",
        "calories": 440, "protein": 34, "carbs": 28, "fat": 22, "fiber": 3,
        "ingredients": [
            {"name": "Haehnchenkeulen", "quantity": "4", "unit": "Stueck"},
            {"name": "Kartoffeln", "quantity": "500", "unit": "g"},
            {"name": "Zitronen", "quantity": "2", "unit": "Stueck"},
            {"name": "Oliven (schwarz)", "quantity": "100", "unit": "g"},
            {"name": "Knoblauch", "quantity": "6", "unit": "Zehe"},
            {"name": "Rosmarin", "quantity": "3", "unit": "Stange"},
            {"name": "Olivenoel", "quantity": "3", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Kartoffeln vierteln, Zitronen in Spalten schneiden.",
            "Alles auf einem Backblech verteilen mit Olivenoel, Salz und Pfeffer.",
            "Haehnchenkeulen oben drauf, Rosmarin und Knoblauch dazwischen.",
            "50 Min backen, nach 30 Min die Oliven zugeben.",
            "Haehnchen soll goldbraun und knusprig sein.",
        ],
    },
    {
        "name": "Pasta Pesto Genovese",
        "description": "Frisches Basilikum-Pesto mit Pinienkernen und Parmesan auf al-dente Pasta.",
        "image_url": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 10, "servings": 4, "difficulty": "easy",
        "calories": 480, "protein": 16, "carbs": 52, "fat": 24, "fiber": 3,
        "ingredients": [
            {"name": "Spaghetti", "quantity": "400", "unit": "g"},
            {"name": "Basilikum", "quantity": "2", "unit": "Bund"},
            {"name": "Pinienkerne", "quantity": "40", "unit": "g"},
            {"name": "Parmesan", "quantity": "60", "unit": "g"},
            {"name": "Knoblauch", "quantity": "1", "unit": "Zehe"},
            {"name": "Olivenoel", "quantity": "80", "unit": "ml"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Pinienkerne ohne Fett goldbraun roesten.",
            "Basilikum, Pinienkerne, Parmesan, Knoblauch und Salz im Mixer grob zerkleinern.",
            "Olivenoel langsam einlaufen lassen bis eine cremige Paste entsteht.",
            "Spaghetti al dente kochen, 2 EL Nudelwasser aufheben.",
            "Pesto mit dem Nudelwasser verduennen, unter die Pasta heben.",
            "Sofort servieren mit extra Parmesan.",
        ],
    },
    {
        "name": "Asiatische Brokkoli-Rindfleisch-Pfanne",
        "description": "Zarte Rindfleischstreifen mit Brokkoli in einer wuerzigen Knoblauch-Soja-Sauce.",
        "image_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 10, "servings": 4, "difficulty": "easy",
        "calories": 350, "protein": 30, "carbs": 18, "fat": 18, "fiber": 3,
        "ingredients": [
            {"name": "Rindfleisch (Hueftsteak)", "quantity": "500", "unit": "g"},
            {"name": "Brokkoli", "quantity": "400", "unit": "g"},
            {"name": "Sojasauce", "quantity": "3", "unit": "EL"},
            {"name": "Austersauce", "quantity": "2", "unit": "EL"},
            {"name": "Knoblauch", "quantity": "3", "unit": "Zehe"},
            {"name": "Ingwer", "quantity": "1", "unit": "EL"},
            {"name": "Speisestaerke", "quantity": "1", "unit": "EL"},
            {"name": "Sesamoel", "quantity": "1", "unit": "EL"},
            {"name": "Oel", "quantity": "2", "unit": "EL"},
            {"name": "Sesam", "quantity": "1", "unit": "EL"},
        ],
        "instructions": [
            "Rindfleisch gegen die Faser in duenne Streifen schneiden.",
            "Mit 1 EL Sojasauce und Speisestaerke marinieren.",
            "Brokkoli in Roeschen teilen, 2 Min blanchieren.",
            "Oel im Wok erhitzen, Fleisch portionsweise scharf anbraten.",
            "Knoblauch und Ingwer kurz anbraten, Brokkoli zugeben.",
            "Restliche Sojasauce und Austersauce zufuegen, 2 Min schwenken.",
            "Mit Sesamoel und Sesam servieren.",
        ],
    },
    {
        "name": "Baked Feta Pasta",
        "description": "TikTok-Hit: Feta im Ofen mit Tomaten geschmolzen, dann mit Pasta vermengt.",
        "image_url": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop",
        "prep_time": 5, "cook_time": 30, "servings": 4, "difficulty": "easy",
        "calories": 450, "protein": 16, "carbs": 52, "fat": 20, "fiber": 4,
        "ingredients": [
            {"name": "Kirschtomaten", "quantity": "500", "unit": "g"},
            {"name": "Feta", "quantity": "200", "unit": "g"},
            {"name": "Penne", "quantity": "400", "unit": "g"},
            {"name": "Knoblauch", "quantity": "3", "unit": "Zehe"},
            {"name": "Olivenoel", "quantity": "3", "unit": "EL"},
            {"name": "Basilikum", "quantity": "1", "unit": "Bund"},
            {"name": "Chiliflocken", "quantity": "1", "unit": "Prise"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Kirschtomaten in eine Auflaufform, Knoblauch und Olivenoel dazu.",
            "Feta als Block in die Mitte setzen.",
            "25-30 Min backen bis die Tomaten platzen.",
            "Waehrenddessen Penne al dente kochen.",
            "Feta und Tomaten mit einer Gabel vermengen, Chiliflocken und Basilikum dazu.",
            "Pasta unterheben, sofort servieren.",
        ],
    },
    {
        "name": "Currywurst mit Pommes",
        "description": "Deutsche Kultmahlzeit: knackige Bratwurst mit hausgemachter Currysauce und Pommes.",
        "image_url": "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 580, "protein": 20, "carbs": 48, "fat": 34, "fiber": 3,
        "ingredients": [
            {"name": "Bratwurst", "quantity": "4", "unit": "Stueck"},
            {"name": "Pommes (TK)", "quantity": "600", "unit": "g"},
            {"name": "Ketchup", "quantity": "200", "unit": "ml"},
            {"name": "Currypulver", "quantity": "2", "unit": "EL"},
            {"name": "Paprikapulver", "quantity": "1", "unit": "TL"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Apfelsaft", "quantity": "50", "unit": "ml"},
            {"name": "Worcestersauce", "quantity": "1", "unit": "TL"},
            {"name": "Oel", "quantity": "2", "unit": "EL"},
        ],
        "instructions": [
            "Pommes nach Packungsanweisung im Ofen backen.",
            "Bratwuerste in Oel von allen Seiten braun braten.",
            "Zwiebel fein wuerfeln, in derselben Pfanne anschwitzen.",
            "Ketchup, Currypulver, Paprika, Apfelsaft und Worcestersauce zuruehren.",
            "5 Min koecheln lassen.",
            "Bratwurst in Scheiben schneiden, mit Sauce und Pommes servieren.",
            "Extra Currypulver darueber streuen.",
        ],
    },
    {
        "name": "Kartoffelsuppe mit Wuerstchen",
        "description": "Deftige deutsche Kartoffelsuppe mit Wuerstchen und Lauch — purer Comfort Food.",
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 25, "servings": 6, "difficulty": "easy",
        "calories": 380, "protein": 14, "carbs": 36, "fat": 20, "fiber": 4,
        "ingredients": [
            {"name": "Kartoffeln", "quantity": "1", "unit": "kg"},
            {"name": "Wiener Wuerstchen", "quantity": "4", "unit": "Stueck"},
            {"name": "Lauch", "quantity": "1", "unit": "Stange"},
            {"name": "Karotten", "quantity": "2", "unit": "Stueck"},
            {"name": "Sellerie", "quantity": "100", "unit": "g"},
            {"name": "Sahne", "quantity": "100", "unit": "ml"},
            {"name": "Gemuese bruehe", "quantity": "1", "unit": "l"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Petersilie", "quantity": "1", "unit": "Bund"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Kartoffeln, Karotten und Sellerie wuerfeln.",
            "Lauch in Ringe schneiden.",
            "In Bruehe 20 Min weich kochen.",
            "Einen Teil der Suppe grob stampfen (nicht pueerieren — stueckig lassen).",
            "Sahne und Muskatnuss einruehren.",
            "Wuerstchen in Scheiben schneiden, 5 Min mitkoecheln.",
            "Mit Petersilie servieren.",
        ],
    },
    {
        "name": "Spinat-Ricotta-Cannelloni",
        "description": "Ueberbackene Cannelloni gefuellt mit Spinat und Ricotta in Tomatensauce.",
        "image_url": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&h=600&fit=crop",
        "prep_time": 25, "cook_time": 35, "servings": 4, "difficulty": "medium",
        "calories": 420, "protein": 20, "carbs": 38, "fat": 22, "fiber": 4,
        "ingredients": [
            {"name": "Cannelloni", "quantity": "250", "unit": "g"},
            {"name": "Blattspinat", "quantity": "400", "unit": "g"},
            {"name": "Ricotta", "quantity": "250", "unit": "g"},
            {"name": "Passierte Tomaten", "quantity": "500", "unit": "ml"},
            {"name": "Mozzarella", "quantity": "150", "unit": "g"},
            {"name": "Parmesan", "quantity": "40", "unit": "g"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Olivenoel", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Spinat in einer Pfanne zusammenfallen lassen, abkuehlen und ausdruecken.",
            "Ricotta, Spinat, Parmesan, Knoblauch und Muskatnuss mischen.",
            "Tomatensauce mit Salz wuerzen, Haelfte in eine Auflaufform giessen.",
            "Cannelloni mit der Spinat-Ricotta-Masse fuellen.",
            "In die Form legen, restliche Tomatensauce darueber.",
            "Mozzarella darueber verteilen.",
            "Bei 180°C 35 Min ueberbacken.",
        ],
    },
    {
        "name": "Honig-Senf-Lachs mit Spargel",
        "description": "Ofenlachs mit Honig-Senf-Glasur und knackigem gruenen Spargel.",
        "image_url": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 360, "protein": 34, "carbs": 12, "fat": 20, "fiber": 2,
        "ingredients": [
            {"name": "Lachsfilet", "quantity": "4", "unit": "Stueck"},
            {"name": "Gruener Spargel", "quantity": "400", "unit": "g"},
            {"name": "Honig", "quantity": "2", "unit": "EL"},
            {"name": "Dijon-Senf", "quantity": "2", "unit": "EL"},
            {"name": "Sojasauce", "quantity": "1", "unit": "EL"},
            {"name": "Knoblauch", "quantity": "1", "unit": "Zehe"},
            {"name": "Olivenoel", "quantity": "2", "unit": "EL"},
            {"name": "Sesam", "quantity": "1", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Honig, Senf, Sojasauce und gepressten Knoblauch verruehren.",
            "Spargel unten schaelen, mit Olivenoel und Salz auf ein Blech legen.",
            "Lachs dazulegen, mit der Honig-Senf-Glasur bestreichen.",
            "15 Min backen.",
            "Mit Sesam bestreuen und servieren.",
        ],
    },
    {
        "name": "Caprese-Haehnchen",
        "description": "Ueberbackenes Haehnchenfilet mit Tomate, Mozzarella und Basilikum.",
        "image_url": "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 40, "carbs": 6, "fat": 22, "fiber": 1,
        "ingredients": [
            {"name": "Haehnchenbrustfilet", "quantity": "4", "unit": "Stueck"},
            {"name": "Mozzarella", "quantity": "200", "unit": "g"},
            {"name": "Tomaten", "quantity": "2", "unit": "Stueck"},
            {"name": "Basilikum", "quantity": "1", "unit": "Bund"},
            {"name": "Balsamico-Creme", "quantity": "2", "unit": "EL"},
            {"name": "Olivenoel", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Haehnchen salzen, pfeffern, in Olivenoel von beiden Seiten 3 Min anbraten.",
            "In eine Auflaufform legen.",
            "Tomatenscheiben und Mozzarella auf das Haehnchen schichten.",
            "15-20 Min im Ofen backen bis der Kaese geschmolzen ist.",
            "Mit Basilikum und Balsamico-Creme servieren.",
        ],
    },
    {
        "name": "Gulaschsuppe",
        "description": "Feurig-deftige ungarische Gulaschsuppe mit Kartoffeln und viel Paprika.",
        "image_url": "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 90, "servings": 6, "difficulty": "easy",
        "calories": 380, "protein": 28, "carbs": 22, "fat": 18, "fiber": 4,
        "ingredients": [
            {"name": "Rindfleisch (Schulter)", "quantity": "500", "unit": "g"},
            {"name": "Kartoffeln", "quantity": "400", "unit": "g"},
            {"name": "Paprika rot", "quantity": "2", "unit": "Stueck"},
            {"name": "Zwiebeln", "quantity": "2", "unit": "Stueck"},
            {"name": "Tomatenmark", "quantity": "2", "unit": "EL"},
            {"name": "Paprikapulver", "quantity": "3", "unit": "EL"},
            {"name": "Kuemmel", "quantity": "1", "unit": "TL"},
            {"name": "Rinderfond", "quantity": "1.5", "unit": "l"},
            {"name": "Oel", "quantity": "3", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Rindfleisch in 2cm Wuerfel schneiden.",
            "Zwiebeln wuerfeln, in Oel goldbraun braten.",
            "Fleisch scharf anbraten.",
            "Tomatenmark und Paprikapulver kurz mitroesten.",
            "Mit Rinderfond abloeschen, Kuemmel zugeben.",
            "60 Min koecheln lassen.",
            "Kartoffeln und Paprika wuerfeln, letzte 30 Min mitkochen.",
            "Abschmecken und mit frischem Brot servieren.",
        ],
    },
    {
        "name": "Kaesefondue",
        "description": "Schweizer Kaesefondue mit Gruyere und Emmentaler — gesellig und koestlich.",
        "image_url": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 520, "protein": 28, "carbs": 16, "fat": 36, "fiber": 1,
        "ingredients": [
            {"name": "Gruyere", "quantity": "200", "unit": "g"},
            {"name": "Emmentaler", "quantity": "200", "unit": "g"},
            {"name": "Weisswein", "quantity": "200", "unit": "ml"},
            {"name": "Knoblauch", "quantity": "1", "unit": "Zehe"},
            {"name": "Speisestaerke", "quantity": "1", "unit": "EL"},
            {"name": "Kirschwasser", "quantity": "1", "unit": "EL"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Baguette", "quantity": "1", "unit": "Stueck"},
        ],
        "instructions": [
            "Kaese grob reiben.",
            "Fonduetopf mit Knoblauch ausreiben.",
            "Weisswein erhitzen (nicht kochen).",
            "Kaese portionsweise einruehren bis geschmolzen.",
            "Speisestaerke mit Kirschwasser anruehren, unterruehren.",
            "Mit Muskatnuss wuerzen.",
            "Baguette in Stuecke schneiden und eintunken.",
        ],
    },
    {
        "name": "Bananen-Smoothie-Bowl",
        "description": "Dicke Smoothie-Bowl aus gefrorenen Bananen mit Granola und frischen Fruechten.",
        "image_url": "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 0, "servings": 2, "difficulty": "easy",
        "calories": 340, "protein": 8, "carbs": 58, "fat": 10, "fiber": 6,
        "ingredients": [
            {"name": "Bananen (gefroren)", "quantity": "3", "unit": "Stueck"},
            {"name": "Milch", "quantity": "80", "unit": "ml"},
            {"name": "Erdnussbutter", "quantity": "1", "unit": "EL"},
            {"name": "Granola", "quantity": "40", "unit": "g"},
            {"name": "Blaubeeren", "quantity": "50", "unit": "g"},
            {"name": "Kokosflocken", "quantity": "1", "unit": "EL"},
            {"name": "Honig", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Gefrorene Bananen mit Milch und Erdnussbutter im Mixer pueerieren.",
            "Nur so viel Milch zugeben dass es dickfluessig bleibt (nicht fluessig!).",
            "In Schalen fuellen.",
            "Mit Granola, Blaubeeren und Kokosflocken toppen.",
            "Mit Honig betraeufeln. Sofort essen.",
        ],
    },
    {
        "name": "Cordon Bleu",
        "description": "Paniertes Schnitzel gefuellt mit Schinken und schmelzendem Kaese.",
        "image_url": "https://images.unsplash.com/photo-1599921841143-819065a55cc6?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 15, "servings": 4, "difficulty": "medium",
        "calories": 560, "protein": 40, "carbs": 24, "fat": 32, "fiber": 1,
        "ingredients": [
            {"name": "Schweineschnitzel", "quantity": "4", "unit": "Stueck"},
            {"name": "Kochschinken", "quantity": "4", "unit": "Scheibe"},
            {"name": "Emmentaler", "quantity": "4", "unit": "Scheibe"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Semmelbroesel", "quantity": "150", "unit": "g"},
            {"name": "Mehl", "quantity": "80", "unit": "g"},
            {"name": "Butterschmalz", "quantity": "150", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Schnitzel aufschneiden (Tasche bilden, nicht durchschneiden).",
            "Je eine Scheibe Schinken und Kaese hineinlegen.",
            "Zuklappen, mit Zahnstochern fixieren.",
            "Salzen und pfeffern.",
            "In Mehl, Ei und Semmelbroesel panieren.",
            "In heissem Butterschmalz von jeder Seite 5-6 Min goldbraun braten.",
            "Auf Kuechenpapier abtropfen lassen, Zahnstocher entfernen.",
        ],
    },
    {
        "name": "Erbsensuppe mit Minze",
        "description": "Frische Erbsensuppe mit Minze und Creme fraiche — fruehlingshaft und leicht.",
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop",
        "prep_time": 5, "cook_time": 15, "servings": 4, "difficulty": "easy",
        "calories": 200, "protein": 10, "carbs": 22, "fat": 8, "fiber": 6,
        "ingredients": [
            {"name": "Erbsen (TK)", "quantity": "500", "unit": "g"},
            {"name": "Gemuese bruehe", "quantity": "500", "unit": "ml"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Minze", "quantity": "1", "unit": "Bund"},
            {"name": "Creme fraiche", "quantity": "4", "unit": "EL"},
            {"name": "Butter", "quantity": "20", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Zwiebel in Butter anschwitzen.",
            "Erbsen und Bruehe zugeben, 10 Min kochen.",
            "Minze (Stiele entfernen) zugeben.",
            "Fein pueerieren.",
            "Mit Salz und Pfeffer abschmecken.",
            "Mit einem Klecks Creme fraiche und Minzblaettern servieren.",
        ],
    },
    {
        "name": "Doener-Bowl",
        "description": "Alle Doener-Zutaten als gesunde Bowl mit Reis, Salat und Knoblauchsauce.",
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 10, "servings": 4, "difficulty": "easy",
        "calories": 460, "protein": 28, "carbs": 42, "fat": 20, "fiber": 4,
        "ingredients": [
            {"name": "Haehnchenbrustfilet", "quantity": "500", "unit": "g"},
            {"name": "Reis", "quantity": "250", "unit": "g"},
            {"name": "Eisbergsalat", "quantity": "200", "unit": "g"},
            {"name": "Tomaten", "quantity": "2", "unit": "Stueck"},
            {"name": "Rotkohl", "quantity": "100", "unit": "g"},
            {"name": "Gurke", "quantity": "1", "unit": "Stueck"},
            {"name": "Joghurt", "quantity": "200", "unit": "g"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Doener-Gewuerz", "quantity": "2", "unit": "EL"},
            {"name": "Olivenoel", "quantity": "2", "unit": "EL"},
        ],
        "instructions": [
            "Reis kochen.",
            "Haehnchen in Streifen schneiden, mit Doener-Gewuerz und Olivenoel wuerzen.",
            "In heisser Pfanne 4 Min pro Seite braten.",
            "Knoblauchsauce: Joghurt mit gepresstem Knoblauch und Salz mischen.",
            "Salat, Tomaten, Gurke und Rotkohl klein schneiden.",
            "Bowls: Reis, Salat, Haehnchen, Gemuese anrichten.",
            "Knoblauchsauce darueber geben.",
        ],
    },
    {
        "name": "Kaesekuchen ohne Boden",
        "description": "Cremiger New-York-Style Kaesekuchen — einfach, ohne Boden, purer Genuss.",
        "image_url": "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 60, "servings": 12, "difficulty": "easy",
        "calories": 300, "protein": 8, "carbs": 28, "fat": 18, "fiber": 0,
        "ingredients": [
            {"name": "Quark", "quantity": "500", "unit": "g"},
            {"name": "Sahne", "quantity": "200", "unit": "ml"},
            {"name": "Eier", "quantity": "3", "unit": "Stueck"},
            {"name": "Zucker", "quantity": "120", "unit": "g"},
            {"name": "Vanillezucker", "quantity": "1", "unit": "Packung"},
            {"name": "Speisestaerke", "quantity": "2", "unit": "EL"},
            {"name": "Zitrone", "quantity": "0.5", "unit": "Stueck"},
            {"name": "Butter", "quantity": "20", "unit": "g"},
        ],
        "instructions": [
            "Backofen auf 160°C vorheizen. Springform (26cm) einfetten.",
            "Quark, Sahne, Zucker und Vanillezucker cremig ruehren.",
            "Eier einzeln unterruehren.",
            "Speisestaerke und Zitronensaft unterheben.",
            "In die Form fuellen.",
            "55-60 Min backen (Oberflaeche soll leicht fest, Mitte noch wackelig sein).",
            "Im ausgeschalteten Ofen mit leicht geoeffneter Tuer abkuehlen lassen.",
            "Mindestens 4 Stunden kuehlen vor dem Servieren.",
        ],
    },
    {
        "name": "Pad Thai",
        "description": "Thailaendisches Nudelgericht mit Garnelen, Erdnuessen und Tamarindensauce.",
        "image_url": "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 10, "servings": 4, "difficulty": "medium",
        "calories": 420, "protein": 22, "carbs": 48, "fat": 16, "fiber": 3,
        "ingredients": [
            {"name": "Reisnudeln", "quantity": "250", "unit": "g"},
            {"name": "Garnelen", "quantity": "200", "unit": "g"},
            {"name": "Tofu", "quantity": "150", "unit": "g"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Sojasprossen", "quantity": "100", "unit": "g"},
            {"name": "Fruehlingszwiebeln", "quantity": "3", "unit": "Stueck"},
            {"name": "Erdnuesse", "quantity": "40", "unit": "g"},
            {"name": "Tamarindenpaste", "quantity": "2", "unit": "EL"},
            {"name": "Fischsauce", "quantity": "2", "unit": "EL"},
            {"name": "Zucker", "quantity": "1", "unit": "EL"},
            {"name": "Limette", "quantity": "1", "unit": "Stueck"},
            {"name": "Oel", "quantity": "2", "unit": "EL"},
        ],
        "instructions": [
            "Reisnudeln in warmem Wasser 15 Min einweichen, abgiessen.",
            "Sauce: Tamarindenpaste, Fischsauce und Zucker verruehren.",
            "Tofu wuerfeln, in Oel goldbraun braten. Herausnehmen.",
            "Garnelen 2 Min braten, zur Seite.",
            "Eier in die Pfanne schlagen, ruehren.",
            "Nudeln und Sauce zugeben, 2 Min schwenken.",
            "Tofu, Garnelen, Sprossen und Fruehlingszwiebeln unterheben.",
            "Mit Erdnuessen und Limette servieren.",
        ],
    },
    {
        "name": "Schweinefilet im Speckmantel",
        "description": "Zartes Schweinefilet umwickelt mit knusprigem Speck, im Ofen gegart.",
        "image_url": "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 380, "protein": 40, "carbs": 2, "fat": 22, "fiber": 0,
        "ingredients": [
            {"name": "Schweinefilet", "quantity": "600", "unit": "g"},
            {"name": "Fruehstuecksspeck", "quantity": "12", "unit": "Scheibe"},
            {"name": "Rosmarin", "quantity": "2", "unit": "Stange"},
            {"name": "Olivenoel", "quantity": "1", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Filet salzen und pfeffern.",
            "Rosmarinnadeln auf den Speck legen, Filet darin einwickeln.",
            "In heissem Olivenoel rundherum 3 Min anbraten.",
            "20-25 Min im Ofen garen (Kerntemperatur 62°C).",
            "5 Min ruhen lassen, dann in Scheiben aufschneiden.",
        ],
    },
    {
        "name": "Linsen-Dal",
        "description": "Cremiges indisches Linsengericht mit Kokosmilch und aromatischen Gewuerzen.",
        "image_url": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 320, "protein": 16, "carbs": 40, "fat": 10, "fiber": 10,
        "ingredients": [
            {"name": "Rote Linsen", "quantity": "250", "unit": "g"},
            {"name": "Kokosmilch", "quantity": "200", "unit": "ml"},
            {"name": "Passierte Tomaten", "quantity": "200", "unit": "ml"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Ingwer", "quantity": "1", "unit": "EL"},
            {"name": "Kurkuma", "quantity": "1", "unit": "TL"},
            {"name": "Kreuzkuemmel", "quantity": "1", "unit": "TL"},
            {"name": "Garam Masala", "quantity": "1", "unit": "TL"},
            {"name": "Koriander", "quantity": "1", "unit": "Bund"},
            {"name": "Basmati-Reis", "quantity": "300", "unit": "g"},
        ],
        "instructions": [
            "Reis kochen.",
            "Zwiebel, Knoblauch und Ingwer anschwitzen.",
            "Kurkuma und Kreuzkuemmel 1 Min mitroesten.",
            "Linsen, Tomaten und 400ml Wasser zugeben.",
            "20 Min koecheln bis Linsen weich sind.",
            "Kokosmilch und Garam Masala einruehren.",
            "Mit Koriander und Reis servieren.",
        ],
    },
    {
        "name": "Thunfisch-Steak mit Sesamkruste",
        "description": "Kurz gebratenes Thunfischsteak mit schwarzem Sesam — innen rosarot.",
        "image_url": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=600&fit=crop",
        "prep_time": 5, "cook_time": 4, "servings": 4, "difficulty": "easy",
        "calories": 280, "protein": 36, "carbs": 4, "fat": 12, "fiber": 1,
        "ingredients": [
            {"name": "Thunfischsteak", "quantity": "4", "unit": "Stueck"},
            {"name": "Schwarzer Sesam", "quantity": "4", "unit": "EL"},
            {"name": "Weisser Sesam", "quantity": "2", "unit": "EL"},
            {"name": "Sojasauce", "quantity": "2", "unit": "EL"},
            {"name": "Wasabi", "quantity": "1", "unit": "TL"},
            {"name": "Sesamoel", "quantity": "1", "unit": "EL"},
            {"name": "Oel", "quantity": "2", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Thunfisch in der Sojasauce kurz marinieren.",
            "Sesam (schwarz und weiss) auf einem Teller mischen.",
            "Thunfisch von allen Seiten in Sesam druecken.",
            "Oel in einer Pfanne stark erhitzen.",
            "Jede Seite nur 60-90 Sekunden braten (innen soll er rosa bleiben).",
            "In Scheiben schneiden, mit Wasabi und Sesamoel servieren.",
        ],
    },
    {
        "name": "Suedtiroler Knoedel",
        "description": "Fluffige Semmelknoedel mit Speck, serviert in kraeftiger Rinderbruehe.",
        "image_url": "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 15, "servings": 4, "difficulty": "medium",
        "calories": 380, "protein": 16, "carbs": 38, "fat": 18, "fiber": 2,
        "ingredients": [
            {"name": "Semmelwuerfel", "quantity": "300", "unit": "g"},
            {"name": "Milch", "quantity": "200", "unit": "ml"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Speckwuerfel", "quantity": "100", "unit": "g"},
            {"name": "Zwiebel", "quantity": "1", "unit": "Stueck"},
            {"name": "Petersilie", "quantity": "1", "unit": "Bund"},
            {"name": "Mehl", "quantity": "2", "unit": "EL"},
            {"name": "Rinderbruehe", "quantity": "1", "unit": "l"},
            {"name": "Butter", "quantity": "20", "unit": "g"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Milch erwaermen, ueber Semmelwuerfel giessen, 15 Min einweichen.",
            "Speck und Zwiebel in Butter anbraten.",
            "Zu den Semmeln geben, Eier, Mehl, Petersilie und Muskat unterruehren.",
            "Salzen und mit feuchten Haenden Knoedel formen.",
            "In siedendem (nicht kochendem!) Salzwasser 15 Min ziehen lassen.",
            "In Rinderbruehe servieren oder als Beilage zu Braten.",
        ],
    },
    {
        "name": "Pasta alla Norma",
        "description": "Sizilianische Pasta mit gebratener Aubergine, Tomaten und Ricotta Salata.",
        "image_url": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop",
        "prep_time": 10, "cook_time": 20, "servings": 4, "difficulty": "easy",
        "calories": 420, "protein": 14, "carbs": 56, "fat": 16, "fiber": 5,
        "ingredients": [
            {"name": "Rigatoni", "quantity": "400", "unit": "g"},
            {"name": "Aubergine", "quantity": "2", "unit": "Stueck"},
            {"name": "Passierte Tomaten", "quantity": "400", "unit": "ml"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Basilikum", "quantity": "1", "unit": "Bund"},
            {"name": "Ricotta Salata (oder Feta)", "quantity": "80", "unit": "g"},
            {"name": "Olivenoel", "quantity": "5", "unit": "EL"},
            {"name": "Chiliflocken", "quantity": "1", "unit": "Prise"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Aubergine in 1cm Wuerfel schneiden, salzen, 10 Min ziehen lassen.",
            "Abtupfen und in Olivenoel portionsweise goldbraun braten.",
            "Knoblauch in Oel anschwitzen, Tomaten zugiessen, 10 Min koecheln.",
            "Rigatoni al dente kochen.",
            "Aubergine zur Tomatensauce geben, Pasta unterheben.",
            "Mit Ricotta Salata und Basilikum servieren.",
        ],
    },
    {
        "name": "French Toast",
        "description": "Goldbraun gebratener French Toast mit Zimt-Zucker und Ahornsirup.",
        "image_url": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=600&fit=crop",
        "prep_time": 5, "cook_time": 10, "servings": 4, "difficulty": "easy",
        "calories": 350, "protein": 10, "carbs": 44, "fat": 14, "fiber": 1,
        "ingredients": [
            {"name": "Toastbrot (dick geschnitten)", "quantity": "8", "unit": "Scheibe"},
            {"name": "Eier", "quantity": "3", "unit": "Stueck"},
            {"name": "Milch", "quantity": "100", "unit": "ml"},
            {"name": "Zimt", "quantity": "1", "unit": "TL"},
            {"name": "Zucker", "quantity": "2", "unit": "EL"},
            {"name": "Butter", "quantity": "30", "unit": "g"},
            {"name": "Ahornsirup", "quantity": "4", "unit": "EL"},
            {"name": "Puderzucker", "quantity": "1", "unit": "EL"},
        ],
        "instructions": [
            "Eier mit Milch, Zimt und Zucker verquirlen.",
            "Toastscheiben kurz in die Eiermischung tauchen (nicht zu lange!).",
            "Butter in einer Pfanne bei mittlerer Hitze schmelzen.",
            "Brotscheiben von jeder Seite 2-3 Min goldbraun braten.",
            "Mit Puderzucker bestauben und Ahornsirup betraeufeln.",
        ],
    },
    {
        "name": "Auberginen-Parmesan",
        "description": "Geschichtete Auberginen mit Tomatensauce und geschmolzenem Mozzarella.",
        "image_url": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&h=600&fit=crop",
        "prep_time": 20, "cook_time": 30, "servings": 4, "difficulty": "medium",
        "calories": 350, "protein": 18, "carbs": 20, "fat": 22, "fiber": 5,
        "ingredients": [
            {"name": "Auberginen", "quantity": "2", "unit": "Stueck"},
            {"name": "Passierte Tomaten", "quantity": "500", "unit": "ml"},
            {"name": "Mozzarella", "quantity": "250", "unit": "g"},
            {"name": "Parmesan", "quantity": "60", "unit": "g"},
            {"name": "Knoblauch", "quantity": "2", "unit": "Zehe"},
            {"name": "Basilikum", "quantity": "1", "unit": "Bund"},
            {"name": "Olivenoel", "quantity": "4", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Auberginen in 1cm Scheiben schneiden, salzen, 15 Min ziehen lassen.",
            "Abtupfen, mit Olivenoel bepinseln, im Ofen bei 200°C 15 Min roesten.",
            "Tomatensauce mit Knoblauch und Basilikum 10 Min koecheln.",
            "In einer Auflaufform schichten: Sauce, Auberginen, Mozzarella — 2-3 Schichten.",
            "Mit Parmesan bestreuen.",
            "25-30 Min bei 180°C ueberbacken.",
        ],
    },
    {
        "name": "Haehnchen-Curry mit Mango",
        "description": "Mildes, fruchtiges Curry mit Haehnchen und frischer Mango.",
        "image_url": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 20, "servings": 4, "difficulty": "easy",
        "calories": 400, "protein": 30, "carbs": 30, "fat": 16, "fiber": 3,
        "ingredients": [
            {"name": "Haehnchenbrustfilet", "quantity": "500", "unit": "g"},
            {"name": "Mango", "quantity": "1", "unit": "Stueck"},
            {"name": "Kokosmilch", "quantity": "400", "unit": "ml"},
            {"name": "Gelbe Currypaste", "quantity": "2", "unit": "EL"},
            {"name": "Paprika rot", "quantity": "1", "unit": "Stueck"},
            {"name": "Fruehlingszwiebeln", "quantity": "3", "unit": "Stueck"},
            {"name": "Limette", "quantity": "1", "unit": "Stueck"},
            {"name": "Koriander", "quantity": "1", "unit": "Bund"},
            {"name": "Basmati-Reis", "quantity": "300", "unit": "g"},
            {"name": "Oel", "quantity": "1", "unit": "EL"},
        ],
        "instructions": [
            "Reis kochen.",
            "Haehnchen wuerfeln, in Oel anbraten.",
            "Currypaste 1 Min mitroesten.",
            "Kokosmilch zugiessen, 10 Min koecheln.",
            "Paprika und Mango in Stuecke schneiden, zugeben.",
            "5 Min weiterkoecheln.",
            "Mit Limettensaft, Koriander und Fruehlingszwiebeln servieren.",
        ],
    },
    {
        "name": "Tacos mit Rindfleisch",
        "description": "Knackige Tacos mit wuerzigem Rinderhack, Guacamole, Salsa und Cheddar.",
        "image_url": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 10, "servings": 4, "difficulty": "easy",
        "calories": 440, "protein": 24, "carbs": 32, "fat": 24, "fiber": 5,
        "ingredients": [
            {"name": "Rinderhackfleisch", "quantity": "400", "unit": "g"},
            {"name": "Taco-Shells", "quantity": "8", "unit": "Stueck"},
            {"name": "Avocado", "quantity": "1", "unit": "Stueck"},
            {"name": "Tomate", "quantity": "2", "unit": "Stueck"},
            {"name": "Eisbergsalat", "quantity": "100", "unit": "g"},
            {"name": "Cheddar", "quantity": "100", "unit": "g"},
            {"name": "Saure Sahne", "quantity": "100", "unit": "g"},
            {"name": "Kreuzkuemmel", "quantity": "1", "unit": "TL"},
            {"name": "Chilipulver", "quantity": "1", "unit": "TL"},
            {"name": "Limette", "quantity": "1", "unit": "Stueck"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Hackfleisch mit Kreuzkuemmel, Chilipulver und Salz kruemelig braten.",
            "Guacamole: Avocado zerdrücken, mit Limettensaft und Salz mischen.",
            "Tomaten wuerfeln fuer Salsa.",
            "Taco-Shells nach Packungsanweisung erwaermen.",
            "Tacos belegen: Hack, Salat, Tomate, Guacamole, Cheddar.",
            "Mit Saurer Sahne toppen.",
        ],
    },
    {
        "name": "Ofenkartoffel mit Sour Cream",
        "description": "Knusprige Ofenkartoffel aufgebrochen mit Sour Cream, Schnittlauch und Cheddar.",
        "image_url": "https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=800&h=600&fit=crop",
        "prep_time": 5, "cook_time": 60, "servings": 4, "difficulty": "easy",
        "calories": 340, "protein": 10, "carbs": 42, "fat": 14, "fiber": 4,
        "ingredients": [
            {"name": "Grosse Kartoffeln", "quantity": "4", "unit": "Stueck"},
            {"name": "Saure Sahne", "quantity": "200", "unit": "g"},
            {"name": "Cheddar", "quantity": "80", "unit": "g"},
            {"name": "Schnittlauch", "quantity": "1", "unit": "Bund"},
            {"name": "Butter", "quantity": "20", "unit": "g"},
            {"name": "Speckwuerfel", "quantity": "80", "unit": "g"},
            {"name": "Olivenoel", "quantity": "1", "unit": "EL"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
        ],
        "instructions": [
            "Backofen auf 200°C vorheizen.",
            "Kartoffeln waschen, einstechen, mit Olivenoel und Salz einreiben.",
            "Direkt auf den Ofenrost 50-60 Min backen.",
            "Speck knusprig braten.",
            "Kartoffeln kreuzweise einschneiden, mit Butter oeffnen.",
            "Saure Sahne, Cheddar, Speck und Schnittlauch darauf geben.",
        ],
    },
    {
        "name": "Nudelauflauf mit Schinken",
        "description": "Cremiger Nudelauflauf mit Schinken und goldbrauner Kaesekruste.",
        "image_url": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&h=600&fit=crop",
        "prep_time": 15, "cook_time": 25, "servings": 4, "difficulty": "easy",
        "calories": 520, "protein": 24, "carbs": 52, "fat": 24, "fiber": 2,
        "ingredients": [
            {"name": "Penne", "quantity": "350", "unit": "g"},
            {"name": "Kochschinken", "quantity": "200", "unit": "g"},
            {"name": "Sahne", "quantity": "200", "unit": "ml"},
            {"name": "Milch", "quantity": "100", "unit": "ml"},
            {"name": "Eier", "quantity": "2", "unit": "Stueck"},
            {"name": "Gouda gerieben", "quantity": "150", "unit": "g"},
            {"name": "Erbsen (TK)", "quantity": "100", "unit": "g"},
            {"name": "Muskatnuss", "quantity": "1", "unit": "Prise"},
            {"name": "Salz", "quantity": "1", "unit": "TL"},
            {"name": "Pfeffer", "quantity": "1", "unit": "Prise"},
        ],
        "instructions": [
            "Penne al dente kochen, abgiessen.",
            "Schinken in Streifen schneiden.",
            "Sahne, Milch, Eier, Haelfte des Gouda, Muskat, Salz und Pfeffer verruehren.",
            "Nudeln, Schinken und Erbsen in eine Auflaufform geben.",
            "Sahne-Ei-Mischung darueber giessen.",
            "Restlichen Gouda darueber streuen.",
            "Bei 200°C 20-25 Min goldbraun ueberbacken.",
        ],
    },
]

def main():
    print(f"Inserting {len(RECIPES)} recipes (batch 2)...")
    success = errors = 0
    for i, recipe in enumerate(RECIPES):
        try:
            rid = insert_recipe(recipe)
            success += 1
            print(f"  [{i+1}/{len(RECIPES)}] {recipe['name']} -> {rid}")
        except Exception as e:
            errors += 1
            print(f"  [{i+1}/{len(RECIPES)}] ERROR: {recipe['name']} -> {e}")
    print(f"\nDone! {success} success, {errors} errors.")

if __name__ == "__main__":
    main()
